# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [5]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
print(np.__version__)

1.19.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [6]:
# Method 1
a = np.random.random((2,3,5))


In [27]:
# Method 2
a = np.random.randint(0,10,(2,3,5))


In [28]:
# Method 3
a = np.arange(30).reshape(2,3,5)


#### 4. Print *a*.


In [7]:
# your code here
a

array([[[0.78960807, 0.77417352, 0.23256333, 0.06066375, 0.06882591],
        [0.9151851 , 0.41161189, 0.88142283, 0.31938687, 0.82710285],
        [0.31429126, 0.1405836 , 0.28503983, 0.33980355, 0.94950369]],

       [[0.31699597, 0.72975583, 0.2870843 , 0.49859797, 0.75561683],
        [0.32988196, 0.90167188, 0.74101613, 0.94860947, 0.98280181],
        [0.22805559, 0.4939472 , 0.54649369, 0.79813784, 0.50193448]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [8]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [9]:
# your code here
b
b.shape

(5, 2, 3)

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [10]:
# your code here
len(a) == len (b)

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [11]:
# your answer here
a + b
# not possible because the shape of a (2x3x5) is not the same as the shape of b (5x2x3)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [12]:
# your code here
c = np.transpose(b, (1, 2, 0))


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [24]:
# your code/answer here
d = a + c
d

array([[[1.78960807, 1.77417352, 1.23256333, 1.06066375, 1.06882591],
        [1.9151851 , 1.41161189, 1.88142283, 1.31938687, 1.82710285],
        [1.31429126, 1.1405836 , 1.28503983, 1.33980355, 1.94950369]],

       [[1.31699597, 1.72975583, 1.2870843 , 1.49859797, 1.75561683],
        [1.32988196, 1.90167188, 1.74101613, 1.94860947, 1.98280181],
        [1.22805559, 1.4939472 , 1.54649369, 1.79813784, 1.50193448]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [25]:
# your code/answer here
# d has values between 1 and 2 because a was between 0-1 and c was always =1 
print(a)
print(d)

[[[0.78960807 0.77417352 0.23256333 0.06066375 0.06882591]
  [0.9151851  0.41161189 0.88142283 0.31938687 0.82710285]
  [0.31429126 0.1405836  0.28503983 0.33980355 0.94950369]]

 [[0.31699597 0.72975583 0.2870843  0.49859797 0.75561683]
  [0.32988196 0.90167188 0.74101613 0.94860947 0.98280181]
  [0.22805559 0.4939472  0.54649369 0.79813784 0.50193448]]]
[[[1.78960807 1.77417352 1.23256333 1.06066375 1.06882591]
  [1.9151851  1.41161189 1.88142283 1.31938687 1.82710285]
  [1.31429126 1.1405836  1.28503983 1.33980355 1.94950369]]

 [[1.31699597 1.72975583 1.2870843  1.49859797 1.75561683]
  [1.32988196 1.90167188 1.74101613 1.94860947 1.98280181]
  [1.22805559 1.4939472  1.54649369 1.79813784 1.50193448]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [26]:
# your code here
e = a * c

#### 13. Does *e* equal to *a*? Why or why not?


In [17]:
# your code/answer here

len(e) == len(a) #true

# The resulting array has the same shape because each value in a 
# gets multiplied by the value in the same position in c

True

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [39]:
# your code here
d_max = np.amax(d)
d_min = np.amin(d)
d_mean = np.mean(d)

print(d_min)



1.0606637483062276


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [19]:
# your code here
f = np.empty([2,3,5])


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [36]:
arr = d
arr

array([[[1.78960807, 1.77417352, 1.23256333, 1.06066375, 1.06882591],
        [1.9151851 , 1.41161189, 1.88142283, 1.31938687, 1.82710285],
        [1.31429126, 1.1405836 , 1.28503983, 1.33980355, 1.94950369]],

       [[1.31699597, 1.72975583, 1.2870843 , 1.49859797, 1.75561683],
        [1.32988196, 1.90167188, 1.74101613, 1.94860947, 1.98280181],
        [1.22805559, 1.4939472 , 1.54649369, 1.79813784, 1.50193448]]])

In [61]:
# your code here

# conditions = [ d(i) < d_min, 
#               (d(i) < d_mean) & (d(i) > d_min),
#               d(i) == d_mean,
#               (d(i) > d_mean) & (d(i) < d_max),
#               d(i) > d_max ]
              
# choice = [ 0, 50, 25, 75, 100]

f = np.where(((arr < d_mean) & (arr > d_min)), 25, arr)|((arr < d_min), 0, arr)

f



/home/markaw/miniconda3/envs/ironhack_env/lib/python3.7/site-packages/ipykernel_launcher.py:11: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  # This is added back by InteractiveShellApp.init_path()


ValueError: operands could not be broadcast together with shapes (2,3,5) (3,) 

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here