# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [3]:
import numpy as np

#### 2. Print your NumPy version.

In [5]:
print(np.__version__)

1.19.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [7]:
# Method 1: usign random.
a = np.random.random((2,3,5))
a

array([[[0.89689944, 0.54207704, 0.26040616, 0.83339602, 0.90238299],
        [0.84176741, 0.7775507 , 0.27896176, 0.36423662, 0.62307431],
        [0.08894231, 0.02079869, 0.05311326, 0.04642015, 0.10690374]],

       [[0.60217969, 0.71728192, 0.8652999 , 0.58909467, 0.38293484],
        [0.90752314, 0.85180608, 0.96146075, 0.44644556, 0.92998044],
        [0.83422069, 0.9675448 , 0.21807417, 0.36981374, 0.59143183]]])

In [19]:
# Method 2: using Generator.integers
rng.integers(100, size=(2,3,5))

array([[[84, 17,  8, 86,  2],
        [54,  8, 29, 48, 42],
        [40,  2,  0, 12,  0]],

       [[67, 52, 64, 25, 61],
        [76, 38, 46, 99, 80],
        [98, 37, 68, 95, 65]]])

In [23]:
# Method 3: using randint.
import random
np.random.randint(low=0, high=200, size=(2,3,5))

array([[[ 54, 155, 113,  19, 133],
        [151,  30,  78,   4,  43],
        [ 25, 160, 154, 157,  90]],

       [[170,  87, 178, 118,  42],
        [106, 159,  47,  52,  80],
        [ 24,  81, 189,  76, 142]]])

#### 4. Print *a*.


In [26]:
print(a)

[[[0.89689944 0.54207704 0.26040616 0.83339602 0.90238299]
  [0.84176741 0.7775507  0.27896176 0.36423662 0.62307431]
  [0.08894231 0.02079869 0.05311326 0.04642015 0.10690374]]

 [[0.60217969 0.71728192 0.8652999  0.58909467 0.38293484]
  [0.90752314 0.85180608 0.96146075 0.44644556 0.92998044]
  [0.83422069 0.9675448  0.21807417 0.36981374 0.59143183]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [28]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [29]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [30]:
print(a.size)
print(b.size)

30
30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [31]:
# your answer here: no, we can0t add a and b beacause they have different shapes.
np.add(a,b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [33]:
# your code here
c = np.reshape(b, (2, 3, 5))
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [36]:
# now we can add a and c because they have the same shape. 
d = np.add(a,c)
d

array([[[1.89689944, 1.54207704, 1.26040616, 1.83339602, 1.90238299],
        [1.84176741, 1.7775507 , 1.27896176, 1.36423662, 1.62307431],
        [1.08894231, 1.02079869, 1.05311326, 1.04642015, 1.10690374]],

       [[1.60217969, 1.71728192, 1.8652999 , 1.58909467, 1.38293484],
        [1.90752314, 1.85180608, 1.96146075, 1.44644556, 1.92998044],
        [1.83422069, 1.9675448 , 1.21807417, 1.36981374, 1.59143183]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [50]:
# The difference between the values of a and d is 1, because the values of c were just ones. We have add this ones to the numbers in a.
print("This is a:\n", a)
print()
print("This is d:\n", d)

This is a:
 [[[0.89689944 0.54207704 0.26040616 0.83339602 0.90238299]
  [0.84176741 0.7775507  0.27896176 0.36423662 0.62307431]
  [0.08894231 0.02079869 0.05311326 0.04642015 0.10690374]]

 [[0.60217969 0.71728192 0.8652999  0.58909467 0.38293484]
  [0.90752314 0.85180608 0.96146075 0.44644556 0.92998044]
  [0.83422069 0.9675448  0.21807417 0.36981374 0.59143183]]]

This is d:
 [[[1.89689944 1.54207704 1.26040616 1.83339602 1.90238299]
  [1.84176741 1.7775507  1.27896176 1.36423662 1.62307431]
  [1.08894231 1.02079869 1.05311326 1.04642015 1.10690374]]

 [[1.60217969 1.71728192 1.8652999  1.58909467 1.38293484]
  [1.90752314 1.85180608 1.96146075 1.44644556 1.92998044]
  [1.83422069 1.9675448  1.21807417 1.36981374 1.59143183]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [52]:
e = np.multiply(a,c)
e

array([[[0.89689944, 0.54207704, 0.26040616, 0.83339602, 0.90238299],
        [0.84176741, 0.7775507 , 0.27896176, 0.36423662, 0.62307431],
        [0.08894231, 0.02079869, 0.05311326, 0.04642015, 0.10690374]],

       [[0.60217969, 0.71728192, 0.8652999 , 0.58909467, 0.38293484],
        [0.90752314, 0.85180608, 0.96146075, 0.44644556, 0.92998044],
        [0.83422069, 0.9675448 , 0.21807417, 0.36981374, 0.59143183]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [55]:
# a and e are the same because every positive number multiply by 1 is itself, so a = c * a.
print("This is a:\n", a)
print()
print("This is e:\n", e)

This is a:
 [[[0.89689944 0.54207704 0.26040616 0.83339602 0.90238299]
  [0.84176741 0.7775507  0.27896176 0.36423662 0.62307431]
  [0.08894231 0.02079869 0.05311326 0.04642015 0.10690374]]

 [[0.60217969 0.71728192 0.8652999  0.58909467 0.38293484]
  [0.90752314 0.85180608 0.96146075 0.44644556 0.92998044]
  [0.83422069 0.9675448  0.21807417 0.36981374 0.59143183]]]

This is e:
 [[[0.89689944 0.54207704 0.26040616 0.83339602 0.90238299]
  [0.84176741 0.7775507  0.27896176 0.36423662 0.62307431]
  [0.08894231 0.02079869 0.05311326 0.04642015 0.10690374]]

 [[0.60217969 0.71728192 0.8652999  0.58909467 0.38293484]
  [0.90752314 0.85180608 0.96146075 0.44644556 0.92998044]
  [0.83422069 0.9675448  0.21807417 0.36981374 0.59143183]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [57]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print("This is d:\n", d)
print()
print("Max value of d is:", d_max)
print()
print("Min value of d is:", d_min)
print()
print("The mean of d is:", d_mean)

This is d:
 [[[1.89689944 1.54207704 1.26040616 1.83339602 1.90238299]
  [1.84176741 1.7775507  1.27896176 1.36423662 1.62307431]
  [1.08894231 1.02079869 1.05311326 1.04642015 1.10690374]]

 [[1.60217969 1.71728192 1.8652999  1.58909467 1.38293484]
  [1.90752314 1.85180608 1.96146075 1.44644556 1.92998044]
  [1.83422069 1.9675448  1.21807417 1.36981374 1.59143183]]]

Max value of d is: 1.9675448005884157

Min value of d is: 1.0207986867980487

The mean of d is: 1.5624007608645294


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [60]:
# your code here

f = np.empty((2,3,5))
f

array([[[1.89689944, 1.54207704, 1.26040616, 1.83339602, 1.90238299],
        [1.84176741, 1.7775507 , 1.27896176, 1.36423662, 1.62307431],
        [1.08894231, 1.02079869, 1.05311326, 1.04642015, 1.10690374]],

       [[1.60217969, 1.71728192, 1.8652999 , 1.58909467, 1.38293484],
        [1.90752314, 1.85180608, 1.96146075, 1.44644556, 1.92998044],
        [1.83422069, 1.9675448 , 1.21807417, 1.36981374, 1.59143183]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [1]:
# your code here

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here