# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.19.4


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [20]:
# Method 1
a = np.random.rand(2,3,5)
a

array([[[0.68294954, 0.55675152, 0.17442253, 0.48802364, 0.47312772],
        [0.52325332, 0.42124615, 0.0798351 , 0.4690939 , 0.11737612],
        [0.80814168, 0.16251509, 0.3068028 , 0.14987518, 0.72191606]],

       [[0.08345021, 0.2736893 , 0.94620548, 0.54674891, 0.10596529],
        [0.50046912, 0.10595947, 0.27750868, 0.7101077 , 0.57803339],
        [0.33491509, 0.57854128, 0.88859778, 0.83311718, 0.51977207]]])

In [22]:
# Method 2

a = np.random.randint(0, 100, size=(2,3,5))
a

array([[[29, 54, 82,  0, 91],
        [52, 77, 76, 94, 84],
        [ 2,  6,  9, 56,  6]],

       [[57, 78, 53, 35, 38],
        [67,  8, 96, 57, 84],
        [34, 63, 26, 45,  1]]])

In [ ]:
# Method 3

#### 4. Print *a*.


In [23]:
# your code here

print(a)

[[[29 54 82  0 91]
  [52 77 76 94 84]
  [ 2  6  9 56  6]]

 [[57 78 53 35 38]
  [67  8 96 57 84]
  [34 63 26 45  1]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [17]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [24]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [25]:
# your code here
a.shape == b.shape

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [26]:
# your answer here

#Since they don't have the same shape, it's not possible to add them
c = a + b
c

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [35]:
# your code here
c = b.transpose(1,2,0)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [36]:
# your code/answer here
#Now that they have the same shape, they can be added.
d = a + c
d

array([[[30., 55., 83.,  1., 92.],
        [53., 78., 77., 95., 85.],
        [ 3.,  7., 10., 57.,  7.]],

       [[58., 79., 54., 36., 39.],
        [68.,  9., 97., 58., 85.],
        [35., 64., 27., 46.,  2.]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [37]:
# your code/answer here

print(a)
print(d)

#The array "a" are integer numbers while the array "d" are floats

[[[29 54 82  0 91]
  [52 77 76 94 84]
  [ 2  6  9 56  6]]

 [[57 78 53 35 38]
  [67  8 96 57 84]
  [34 63 26 45  1]]]
[[[30. 55. 83.  1. 92.]
  [53. 78. 77. 95. 85.]
  [ 3.  7. 10. 57.  7.]]

 [[58. 79. 54. 36. 39.]
  [68.  9. 97. 58. 85.]
  [35. 64. 27. 46.  2.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [38]:
# your code here
e = a * c
e

array([[[29., 54., 82.,  0., 91.],
        [52., 77., 76., 94., 84.],
        [ 2.,  6.,  9., 56.,  6.]],

       [[57., 78., 53., 35., 38.],
        [67.,  8., 96., 57., 84.],
        [34., 63., 26., 45.,  1.]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [39]:
# your code/answer here

a == e

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [ ]:
# your code here

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [ ]:
# your code here

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [1]:
# your code here

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here