# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [3]:
# your code here
print(np.__version__)

1.19.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [4]:
# Method 1

a = np.random.random((2,3,5))
a

array([[[0.34064922, 0.21046917, 0.76048093, 0.55078296, 0.38036184],
        [0.78866514, 0.39786102, 0.6326653 , 0.18569582, 0.31556878],
        [0.18662409, 0.81786466, 0.45328892, 0.03779558, 0.05190113]],

       [[0.10004227, 0.87050813, 0.60861475, 0.13549956, 0.77645566],
        [0.5017569 , 0.01523005, 0.30885847, 0.22846639, 0.07182103],
        [0.54802548, 0.6694869 , 0.78934742, 0.00088607, 0.51491847]]])

In [5]:
# Method 2
a = np.random.rand(2,3,5)
a

array([[[0.77240915, 0.14865038, 0.43993178, 0.55240564, 0.17980479],
        [0.19839531, 0.81668844, 0.46640941, 0.95740996, 0.26521734],
        [0.20129579, 0.69271648, 0.05622804, 0.11772317, 0.47981159]],

       [[0.17527117, 0.18346427, 0.54344454, 0.86691328, 0.43062949],
        [0.8427121 , 0.61969408, 0.5052903 , 0.11396442, 0.29948509],
        [0.32940226, 0.97154497, 0.18298351, 0.31106536, 0.6774707 ]]])

In [6]:
# Method 3
a = np.random.randint(100, size =(2,3,5))
a

array([[[ 5, 63,  8, 29, 90],
        [22, 51,  1, 21, 65],
        [80, 75, 30, 63,  7]],

       [[95, 95, 24,  6, 95],
        [75, 60, 29,  2, 76],
        [93, 93, 92, 27, 59]]])

#### 4. Print *a*.


In [7]:
# your code here
# 'a' is printed above for each method 

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [8]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [9]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [10]:
# your code here
# They have the same size. We can check by using 'size' attribute

a.size
b.size

30

#### 8. Are you able to add *a* and *b*? Why or why not?


In [11]:
# your answer here
# Both arrays cannot be 'added' because of their different size.

# a + b. NO!

# However both arrays can be 'appended'. BUT, the result is not a fixed-size array like a or b. 
# It has a different size
np.append(a,b)

array([ 5., 63.,  8., 29., 90., 22., 51.,  1., 21., 65., 80., 75., 30.,
       63.,  7., 95., 95., 24.,  6., 95., 75., 60., 29.,  2., 76., 93.,
       93., 92., 27., 59.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [12]:
# your code here
c = np.reshape(b, (2,3,5))
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [13]:
# your code/answer here

d = a + c
d

array([[[ 6., 64.,  9., 30., 91.],
        [23., 52.,  2., 22., 66.],
        [81., 76., 31., 64.,  8.]],

       [[96., 96., 25.,  7., 96.],
        [76., 61., 30.,  3., 77.],
        [94., 94., 93., 28., 60.]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [14]:
# your code/answer here
print(f'array a = {a} \n\n array d = {d}')

array a = [[[ 5 63  8 29 90]
  [22 51  1 21 65]
  [80 75 30 63  7]]

 [[95 95 24  6 95]
  [75 60 29  2 76]
  [93 93 92 27 59]]] 

 array d = [[[ 6. 64.  9. 30. 91.]
  [23. 52.  2. 22. 66.]
  [81. 76. 31. 64.  8.]]

 [[96. 96. 25.  7. 96.]
  [76. 61. 30.  3. 77.]
  [94. 94. 93. 28. 60.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [15]:
# your code here

e = a * c
e

array([[[ 5., 63.,  8., 29., 90.],
        [22., 51.,  1., 21., 65.],
        [80., 75., 30., 63.,  7.]],

       [[95., 95., 24.,  6., 95.],
        [75., 60., 29.,  2., 76.],
        [93., 93., 92., 27., 59.]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [16]:
# your code/answer here
# Array e is equal to a since we are multiplying an array by ONE

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [25]:
# your code here
print(f'max of d = {np.max(d)}, min of d = {np.min(d)} and mean of d = {np.mean(d)}')

max of d = 96.0, min of d = 2.0 and mean of d = 52.03333333333333


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [31]:
# your code here

f = np.empty((2,3,5))

array([[[ 6., 64.,  9., 30., 91.],
        [23., 52.,  2., 22., 66.],
        [81., 76., 31., 64.,  8.]],

       [[96., 96., 25.,  7., 96.],
        [76., 61., 30.,  3., 77.],
        [94., 94., 93., 28., 60.]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [48]:
# your code here

a = int(np.min(d))
b = int(np.max(d))
c = int(np.mean(d))


    


[array([[ 6., 64.,  9., 30., 91.],
        [23., 52.,  2., 22., 66.],
        [81., 76., 31., 64.,  8.]]),
 array([[96., 96., 25.,  7., 96.],
        [76., 61., 30.,  3., 77.],
        [94., 94., 93., 28., 60.]])]

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here