# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [49]:
import numpy as np

#### 2. Print your NumPy version.

In [50]:
print(np.__version__)

1.18.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [60]:
a = np.random.random((2, 3, 5))
print(a.shape)

(2, 3, 5)


In [61]:
a = np.random.randint(low = 0, high = 101, size = (2, 3, 5))
print(a.shape)

(2, 3, 5)


In [62]:
# Method 3

#### 4. Print *a*.


In [63]:
print(a)

[[[40 43 67 89 90]
  [34 88 81 94 99]
  [23 61 55  0 97]]

 [[17 14 53 35 79]
  [76 61 24 60 51]
  [85 75 20 68 88]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [64]:
b = np.ones((5, 2, 3))
print(b.shape)

(5, 2, 3)


#### 6. Print *b*.


In [65]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [67]:
print("Tienen el mismo size" if a.size == b.size else "No tienen el mismo size")
print(a.size)
print(b.size)

Tienen el mismo size
30
30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [69]:
# No se pueden sumar directamente porque tienen distintas dimensiones (a tiene 2x3x5 y b 5x2x3)

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [78]:
c = b.transpose((1, 2, 0))
print(c.shape)

(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [80]:
# Podemos sumar matrices con las mismas dimensiones (en este caso ambas tienen 2x3x5)
d = a + c

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [85]:
print(a)
print(d)
# Los valores en d son tipo float porque la matriz b de la que viene c son también floats (concretamente 1.0)

[[[40 43 67 89 90]
  [34 88 81 94 99]
  [23 61 55  0 97]]

 [[17 14 53 35 79]
  [76 61 24 60 51]
  [85 75 20 68 88]]]
[[[ 41.  44.  68.  90.  91.]
  [ 35.  89.  82.  95. 100.]
  [ 24.  62.  56.   1.  98.]]

 [[ 18.  15.  54.  36.  80.]
  [ 77.  62.  25.  61.  52.]
  [ 86.  76.  21.  69.  89.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [91]:
e = a * c
print(e)

[[[40. 43. 67. 89. 90.]
  [34. 88. 81. 94. 99.]
  [23. 61. 55.  0. 97.]]

 [[17. 14. 53. 35. 79.]
  [76. 61. 24. 60. 51.]
  [85. 75. 20. 68. 88.]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [92]:
print(a)
print(e)
# La matriz c es una matriz con unos. Por eso al multiplicar elemento a elemento 
# la matriz a por el elemento de la matriz c nos da el mismo resultado.

[[[40 43 67 89 90]
  [34 88 81 94 99]
  [23 61 55  0 97]]

 [[17 14 53 35 79]
  [76 61 24 60 51]
  [85 75 20 68 88]]]
[[[40. 43. 67. 89. 90.]
  [34. 88. 81. 94. 99.]
  [23. 61. 55.  0. 97.]]

 [[17. 14. 53. 35. 79.]
  [76. 61. 24. 60. 51.]
  [85. 75. 20. 68. 88.]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [93]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print(d_max)
print(d_min)
print(d_mean)

100.0
1.0
59.9


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [98]:
f = np.empty((2, 3, 5))
print(f.shape)

(2, 3, 5)


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [104]:
for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i, j])):
            val = d[i, j, k]
            if val > d_min and val < d_mean:
                f[i, j, k] = 25
            elif val > d_mean and val < d_max:
                f[i, j, k] = 75
            elif val == d_mean:
                f[i, j, k] = 50
            elif val == d_min:
                f[i, j, k] = 0
            else:
                f[i, j, k] = 100


[[[ 41.  44.  68.  90.  91.]
  [ 35.  89.  82.  95. 100.]
  [ 24.  62.  56.   1.  98.]]

 [[ 18.  15.  54.  36.  80.]
  [ 77.  62.  25.  61.  52.]
  [ 86.  76.  21.  69.  89.]]]
[[[ 25.  25.  75.  75.  75.]
  [ 25.  75.  75.  75. 100.]
  [ 25.  75.  25.   0.  75.]]

 [[ 25.  25.  25.  25.  75.]
  [ 75.  75.  25.  75.  25.]
  [ 75.  75.  25.  75.  75.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [105]:
print(d)
print(f)

[[[ 41.  44.  68.  90.  91.]
  [ 35.  89.  82.  95. 100.]
  [ 24.  62.  56.   1.  98.]]

 [[ 18.  15.  54.  36.  80.]
  [ 77.  62.  25.  61.  52.]
  [ 86.  76.  21.  69.  89.]]]
[[[ 25.  25.  75.  75.  75.]
  [ 25.  75.  75.  75. 100.]
  [ 25.  75.  25.   0.  75.]]

 [[ 25.  25.  25.  25.  75.]
  [ 75.  75.  25.  75.  25.]
  [ 75.  75.  25.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [109]:
# Primero creo un nuevo array f
f = np.empty((2, 3, 5))

# Luego le cambio el tipo de datos para que acepte strings
f = f.astype('object')

# Uso el mismo for que en el ejercicio anterior pero con letras
for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i, j])):
            val = d[i, j, k]
            if val > d_min and val < d_mean:
                f[i, j, k] = "B"
            elif val > d_mean and val < d_max:
                f[i, j, k] = "D"
            elif val == d_mean:
                f[i, j, k] = "C"
            elif val == d_min:
                f[i, j, k] = "A"
            else:
                f[i, j, k] = "E"

# Muestro los resultados
print(d)
print(f)

[[[ 41.  44.  68.  90.  91.]
  [ 35.  89.  82.  95. 100.]
  [ 24.  62.  56.   1.  98.]]

 [[ 18.  15.  54.  36.  80.]
  [ 77.  62.  25.  61.  52.]
  [ 86.  76.  21.  69.  89.]]]
[[['B' 'B' 'D' 'D' 'D']
  ['B' 'D' 'D' 'D' 'E']
  ['B' 'D' 'B' 'A' 'D']]

 [['B' 'B' 'B' 'B' 'D']
  ['D' 'D' 'B' 'D' 'B']
  ['D' 'D' 'B' 'D' 'D']]]


# Bonus Katas:
https://www.codewars.com/kata/insert-dashes

In [ ]:
def is_odd(num):
    return int(num) % 2 != 0

def insert_dash(num):
    num_as_str = str(num)
    result = num_as_str[0]
    for i in range(1, len(num_as_str)):
        if is_odd(num_as_str[i - 1]) and is_odd(num_as_str[i]):
            result += "-"
        result += num_as_str[i]
            
    return result

https://www.codewars.com/kata/thinkful-logic-drills-red-and-bumpy

In [ ]:
def color_probability(color, texture):
    prob = {}
    prob["bumpy"] = {}
    prob["smooth"] = {}

    prob["bumpy"]["red"] = 4 / 7
    prob["bumpy"]["yellow"] = 2 / 7
    prob["bumpy"]["green"] = 1 / 7
    
    prob["smooth"]["red"] = 1 / 3
    prob["smooth"]["yellow"] = 1 / 3
    prob["smooth"]["green"] = 1 / 3
    
    return str(prob[texture][color])[:4]