# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.19.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.random((2,3,5))
a

array([[[0.38916254, 0.34639965, 0.10123705, 0.48458719, 0.33424825],
        [0.60454163, 0.58880574, 0.72853346, 0.15629269, 0.2555806 ],
        [0.24529438, 0.54953361, 0.79232536, 0.99731695, 0.47332743]],

       [[0.83420838, 0.69850036, 0.45136179, 0.62307859, 0.1194553 ],
        [0.43376853, 0.4564736 , 0.66690864, 0.26814419, 0.34816989],
        [0.69398924, 0.67140202, 0.5459731 , 0.73852153, 0.49700126]]])

In [4]:
# Method 2
a = np.random.randint(low = 0, high = 50, size = (2,3,5))
a

array([[[46, 30, 12, 46,  0],
        [19, 39, 15,  1, 40],
        [26, 29,  4, 12,  2]],

       [[45, 48,  5, 47, 43],
        [ 4, 37, 20,  3,  6],
        [38,  2,  2, 24, 31]]])

In [5]:
# Method 3
a = np.random.rand(2,3,5)
a

array([[[0.37926134, 0.5088485 , 0.8238377 , 0.45854052, 0.75268375],
        [0.18515418, 0.18786116, 0.0274048 , 0.05265653, 0.62066196],
        [0.38072399, 0.39253597, 0.10146298, 0.37928314, 0.70675168]],

       [[0.491843  , 0.40114451, 0.03573961, 0.15760608, 0.87935126],
        [0.89187821, 0.62704057, 0.7851537 , 0.27157951, 0.88684972],
        [0.89882743, 0.42790924, 0.82469889, 0.0573079 , 0.04492754]]])

#### 4. Print *a*.


In [6]:
# your code here
print(a)

[[[0.37926134 0.5088485  0.8238377  0.45854052 0.75268375]
  [0.18515418 0.18786116 0.0274048  0.05265653 0.62066196]
  [0.38072399 0.39253597 0.10146298 0.37928314 0.70675168]]

 [[0.491843   0.40114451 0.03573961 0.15760608 0.87935126]
  [0.89187821 0.62704057 0.7851537  0.27157951 0.88684972]
  [0.89882743 0.42790924 0.82469889 0.0573079  0.04492754]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [16]:
# your code here
if a.size == b.size:
    print('True')
else:
    print('False')

True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
#No, because their shapes are differents. We would need to reshape one of the array to being able to add them.

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [23]:
#your code here
c = np.reshape(b, (2,3,5))
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [24]:
# your code/answer here
d = np.add(a,c)
d
#It does work now because both arrays have the same shape. 

array([[[1.37926134, 1.5088485 , 1.8238377 , 1.45854052, 1.75268375],
        [1.18515418, 1.18786116, 1.0274048 , 1.05265653, 1.62066196],
        [1.38072399, 1.39253597, 1.10146298, 1.37928314, 1.70675168]],

       [[1.491843  , 1.40114451, 1.03573961, 1.15760608, 1.87935126],
        [1.89187821, 1.62704057, 1.7851537 , 1.27157951, 1.88684972],
        [1.89882743, 1.42790924, 1.82469889, 1.0573079 , 1.04492754]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [25]:
# your code/answer here
print('Array A: ' + str(a))

print('   ')

print('Array D: ' + str(d))

#Array D has the same values as A but with +1.00

Array A: [[[0.37926134 0.5088485  0.8238377  0.45854052 0.75268375]
  [0.18515418 0.18786116 0.0274048  0.05265653 0.62066196]
  [0.38072399 0.39253597 0.10146298 0.37928314 0.70675168]]

 [[0.491843   0.40114451 0.03573961 0.15760608 0.87935126]
  [0.89187821 0.62704057 0.7851537  0.27157951 0.88684972]
  [0.89882743 0.42790924 0.82469889 0.0573079  0.04492754]]]
   
Array D: [[[1.37926134 1.5088485  1.8238377  1.45854052 1.75268375]
  [1.18515418 1.18786116 1.0274048  1.05265653 1.62066196]
  [1.38072399 1.39253597 1.10146298 1.37928314 1.70675168]]

 [[1.491843   1.40114451 1.03573961 1.15760608 1.87935126]
  [1.89187821 1.62704057 1.7851537  1.27157951 1.88684972]
  [1.89882743 1.42790924 1.82469889 1.0573079  1.04492754]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [26]:
# your code here
e = np.multiply(a, c)
e

array([[[0.37926134, 0.5088485 , 0.8238377 , 0.45854052, 0.75268375],
        [0.18515418, 0.18786116, 0.0274048 , 0.05265653, 0.62066196],
        [0.38072399, 0.39253597, 0.10146298, 0.37928314, 0.70675168]],

       [[0.491843  , 0.40114451, 0.03573961, 0.15760608, 0.87935126],
        [0.89187821, 0.62704057, 0.7851537 , 0.27157951, 0.88684972],
        [0.89882743, 0.42790924, 0.82469889, 0.0573079 , 0.04492754]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [27]:
# your code/answer here    
(e == a).all()

True

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [28]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(('max: ') + str(d_max))
print(('min: ') + str(d_min))
print(('mean: ') + str(d_mean))

max: 1.8988274324618597
min: 1.0274047996146056
mean: 1.4546508451036477


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [29]:
# your code here
f = np.empty_like(d)
f

array([[[0.37926134, 0.5088485 , 0.8238377 , 0.45854052, 0.75268375],
        [0.18515418, 0.18786116, 0.0274048 , 0.05265653, 0.62066196],
        [0.38072399, 0.39253597, 0.10146298, 0.37928314, 0.70675168]],

       [[0.491843  , 0.40114451, 0.03573961, 0.15760608, 0.87935126],
        [0.89187821, 0.62704057, 0.7851537 , 0.27157951, 0.88684972],
        [0.89882743, 0.42790924, 0.82469889, 0.0573079 , 0.04492754]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [49]:
# your code here

#print('Min: ' + str(d_min))
#print('Max: ' + str(d_max))
#print('Mean: ' + str(d_mean))

for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
            ele = d[i][j][k]
            if d_min < ele and d_mean > ele:
                f[i][j][k] = 25
            if d_mean < ele and d_max > ele:
                f[i][j][k] = 75
            if ele == d_mean:
                f[i][j][k] = 50
            if ele == d_min:
                f[i][j][k] = 0
            if ele == d_max:
                f[i][j][k] = 100
            #print(str(i) + ' ' + str(j) + ' ' + str(k))
            #print(str(ele) + ' ' + str(f[i][j][k]))


print(f)

[[[ 25.  75.  75.  75.  75.]
  [ 25.  25.   0.  25.  75.]
  [ 25.  25.  25.  25.  75.]]

 [[ 75.  25.  25.  25.  75.]
  [ 75.  75.  75.  25.  75.]
  [100.  25.  75.  25.  25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [52]:
# your code here
print('Array D: ' + str(d))
print(' ')
print('Array F: ' + str(f))

Array D: [[[1.37926134 1.5088485  1.8238377  1.45854052 1.75268375]
  [1.18515418 1.18786116 1.0274048  1.05265653 1.62066196]
  [1.38072399 1.39253597 1.10146298 1.37928314 1.70675168]]

 [[1.491843   1.40114451 1.03573961 1.15760608 1.87935126]
  [1.89187821 1.62704057 1.7851537  1.27157951 1.88684972]
  [1.89882743 1.42790924 1.82469889 1.0573079  1.04492754]]]
 
Array F: [[[ 25.  75.  75.  75.  75.]
  [ 25.  25.   0.  25.  75.]
  [ 25.  25.  25.  25.  75.]]

 [[ 75.  25.  25.  25.  75.]
  [ 75.  75.  75.  25.  75.]
  [100.  25.  75.  25.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [80]:
# your code here
f_update = []

for i in range(len(f)):
    f_update.append([])
    for j in range(len(f[i])):
        f_update[i].append([])
        for k in range(len(f[i][j])):
            ele = f[i][j][k]
            if ele == 75:
                f_update[i][j].append('D')
            if ele == 25:
                f_update[i][j].append('B')
            if ele == 50:
                f_update[i][j].append('C')
            if ele == 100:
                f_update[i][j].append('E')
            if ele == 0:
                f_update[i][j].append('A')
f_update

[[['B', 'D', 'D', 'D', 'D'],
  ['B', 'B', 'A', 'B', 'D'],
  ['B', 'B', 'B', 'B', 'D']],
 [['D', 'B', 'B', 'B', 'D'],
  ['D', 'D', 'D', 'B', 'D'],
  ['E', 'B', 'D', 'B', 'B']]]