# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [3]:
import numpy as np


#### 2. Print your NumPy version.

In [6]:
print(np.__version__)

1.19.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [7]:

a = np.random.random((2,3,5))
a

array([[[0.63808609, 0.16666876, 0.38020612, 0.8959937 , 0.83268248],
        [0.54390804, 0.74350851, 0.81652161, 0.35591646, 0.33812531],
        [0.47012286, 0.47850867, 0.01604536, 0.32376172, 0.06659979]],

       [[0.20364194, 0.24936831, 0.41653886, 0.88532393, 0.6074347 ],
        [0.66559469, 0.88077514, 0.49171928, 0.17516675, 0.76583426],
        [0.13930664, 0.2942106 , 0.86592329, 0.13084321, 0.63868821]]])

In [8]:
a_v2 = np.random.rand(2,3,5)
a_v2


array([[[0.1475635 , 0.11323099, 0.83703586, 0.45322361, 0.69368291],
        [0.21111822, 0.24871729, 0.5185856 , 0.69000923, 0.59864312],
        [0.42066076, 0.97590446, 0.933141  , 0.39957767, 0.18273783]],

       [[0.3234816 , 0.09440356, 0.9728139 , 0.40331657, 0.85275239],
        [0.40363833, 0.56733943, 0.12408303, 0.02014722, 0.6809217 ],
        [0.69530662, 0.58695808, 0.8205789 , 0.82609131, 0.41181011]]])

In [13]:
a_v3 = np.random.ranf((2,3,5))
a_v3

array([[[0.63643449, 0.32515258, 0.15132447, 0.8405824 , 0.26656503],
        [0.16057186, 0.16082588, 0.93671168, 0.09857954, 0.375506  ],
        [0.04776383, 0.26236658, 0.07674634, 0.3342468 , 0.52010769]],

       [[0.00279199, 0.9610401 , 0.72479942, 0.34652854, 0.55928523],
        [0.71298272, 0.14223577, 0.61710878, 0.72352797, 0.90907306],
        [0.63304054, 0.71995539, 0.73740097, 0.36247572, 0.36700874]]])

#### 4. Print *a*.


In [9]:
print(a)


[[[0.63808609 0.16666876 0.38020612 0.8959937  0.83268248]
  [0.54390804 0.74350851 0.81652161 0.35591646 0.33812531]
  [0.47012286 0.47850867 0.01604536 0.32376172 0.06659979]]

 [[0.20364194 0.24936831 0.41653886 0.88532393 0.6074347 ]
  [0.66559469 0.88077514 0.49171928 0.17516675 0.76583426]
  [0.13930664 0.2942106  0.86592329 0.13084321 0.63868821]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [10]:
b = np.ones((5,2,3))
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 6. Print *b*.


In [11]:
print (b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [12]:
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [24]:
# your answer here
# A can'b be added to b because they have different shapes

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [13]:
c = np.reshape(b, (2,3,5))
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [14]:
d = np.add(a, c)
d 
#It works because now they have equal shapes

array([[[1.63808609, 1.16666876, 1.38020612, 1.8959937 , 1.83268248],
        [1.54390804, 1.74350851, 1.81652161, 1.35591646, 1.33812531],
        [1.47012286, 1.47850867, 1.01604536, 1.32376172, 1.06659979]],

       [[1.20364194, 1.24936831, 1.41653886, 1.88532393, 1.6074347 ],
        [1.66559469, 1.88077514, 1.49171928, 1.17516675, 1.76583426],
        [1.13930664, 1.2942106 , 1.86592329, 1.13084321, 1.63868821]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [15]:
print(d)

[[[1.63808609 1.16666876 1.38020612 1.8959937  1.83268248]
  [1.54390804 1.74350851 1.81652161 1.35591646 1.33812531]
  [1.47012286 1.47850867 1.01604536 1.32376172 1.06659979]]

 [[1.20364194 1.24936831 1.41653886 1.88532393 1.6074347 ]
  [1.66559469 1.88077514 1.49171928 1.17516675 1.76583426]
  [1.13930664 1.2942106  1.86592329 1.13084321 1.63868821]]]


In [16]:
print (a)

[[[0.63808609 0.16666876 0.38020612 0.8959937  0.83268248]
  [0.54390804 0.74350851 0.81652161 0.35591646 0.33812531]
  [0.47012286 0.47850867 0.01604536 0.32376172 0.06659979]]

 [[0.20364194 0.24936831 0.41653886 0.88532393 0.6074347 ]
  [0.66559469 0.88077514 0.49171928 0.17516675 0.76583426]
  [0.13930664 0.2942106  0.86592329 0.13084321 0.63868821]]]


In [ ]:
#Same shape and c was addep to d, so d is +1 in every element of the array

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [17]:
e = np.multiply(a, c)
e

array([[[0.63808609, 0.16666876, 0.38020612, 0.8959937 , 0.83268248],
        [0.54390804, 0.74350851, 0.81652161, 0.35591646, 0.33812531],
        [0.47012286, 0.47850867, 0.01604536, 0.32376172, 0.06659979]],

       [[0.20364194, 0.24936831, 0.41653886, 0.88532393, 0.6074347 ],
        [0.66559469, 0.88077514, 0.49171928, 0.17516675, 0.76583426],
        [0.13930664, 0.2942106 , 0.86592329, 0.13084321, 0.63868821]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
#yes because every elemement has been multiplied by 1

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [18]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [19]:
f = np.empty((2,3,5))
f

array([[[0.63808609, 0.16666876, 0.38020612, 0.8959937 , 0.83268248],
        [0.54390804, 0.74350851, 0.81652161, 0.35591646, 0.33812531],
        [0.47012286, 0.47850867, 0.01604536, 0.32376172, 0.06659979]],

       [[0.20364194, 0.24936831, 0.41653886, 0.88532393, 0.6074347 ],
        [0.66559469, 0.88077514, 0.49171928, 0.17516675, 0.76583426],
        [0.13930664, 0.2942106 , 0.86592329, 0.13084321, 0.63868821]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [1]:
# your code here

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here