# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
np.version.version

'1.19.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a_1 = np.random.random((2,3,5))

In [4]:
# Method 2
a_2 = np.random.randint(low=0, high=100, size=(2,3,5))

In [5]:
# Method 3
a_3 = np.random.rand(2,3,5)

#### 4. Print *a*.


In [6]:
# your code here
print(a_1)
print(a_2)
print(a_3)

[[[0.30342303 0.17110038 0.37775875 0.72479454 0.65523651]
  [0.65473405 0.59645495 0.80824868 0.2337549  0.39425582]
  [0.09990304 0.06651544 0.79548964 0.47521282 0.03229182]]

 [[0.87060701 0.10370301 0.57951626 0.06957617 0.29646273]
  [0.1833518  0.05045979 0.24474622 0.32236981 0.69770493]
  [0.4351634  0.71227533 0.7114299  0.84609403 0.84855264]]]
[[[83 14 19 42 60]
  [79 61 79 33 93]
  [88  6 74 25  4]]

 [[47 23 49  3 96]
  [46 92 30 84 97]
  [59 24 81 58 16]]]
[[[0.88341489 0.55625406 0.78666966 0.34375541 0.50271536]
  [0.49627824 0.68278522 0.97789551 0.43307757 0.56034266]
  [0.87006375 0.12807617 0.98858204 0.73596225 0.97478834]]

 [[0.88558356 0.47668682 0.85322208 0.14919383 0.28116717]
  [0.60724805 0.06046008 0.89034102 0.86540738 0.84929641]
  [0.42362393 0.63383577 0.90454446 0.95716396 0.74700037]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [8]:
# your code here
print(b)
b.shape

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


(5, 2, 3)

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
# print(a_1.size)
# print(a_2.size)
# print(a_3.size)
# print(b.size)

if a_1.size == b.size:
    print(True,"- The compared arrays DO have the same size.","a_1.size =",a_1.size, "and","b.size =",b.size)
else:
    print(False,"- The compared arrays DO NOT have the same size.","a_1.size =",a_1.size, "and","b.size =",b.size)
    

True - The compared arrays DO have the same size. a_1.size = 30 and b.size = 30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here

print(a_1 + b)
print(a_2 + b)
print(a_3 + b)

#Arrays can't be added because they are shaped differently. It raises a ValueError:
#ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here
c = np.transpose(b)

#I tried using transpose, but the shape using transpose is different from a.shape. Using transpose it returns a -> c.shape that is (3, 2, 5)
# And we need a 2x3x5 shape. Which are the shapes in a_1,a_2 or a_3, as requested in step #3
'''---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-25-99e5ad4b5996> in <module>
      1 # your code/answer here
----> 2 d = a_1 + c
      3 print(d)

ValueError: operands could not be broadcast together with shapes (2,3,5) (3,2,5)'''

#So I will used the reshape option to shape as needed to add the ones.

c = np.reshape(b,(2,3,5))

print(c.shape)
print(a_1.shape)
print(a_2.shape)
print(a_2.shape)

print(c)


(2, 3, 5)
(2, 3, 5)
(2, 3, 5)
(2, 3, 5)
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
d_1 = a_1 + c
d_2 = a_2 + c
d_3 = a_3 + c
print(d_1)
print(d_2)
print(d_3)

[[[1.30342303 1.17110038 1.37775875 1.72479454 1.65523651]
  [1.65473405 1.59645495 1.80824868 1.2337549  1.39425582]
  [1.09990304 1.06651544 1.79548964 1.47521282 1.03229182]]

 [[1.87060701 1.10370301 1.57951626 1.06957617 1.29646273]
  [1.1833518  1.05045979 1.24474622 1.32236981 1.69770493]
  [1.4351634  1.71227533 1.7114299  1.84609403 1.84855264]]]
[[[84. 15. 20. 43. 61.]
  [80. 62. 80. 34. 94.]
  [89.  7. 75. 26.  5.]]

 [[48. 24. 50.  4. 97.]
  [47. 93. 31. 85. 98.]
  [60. 25. 82. 59. 17.]]]
[[[1.88341489 1.55625406 1.78666966 1.34375541 1.50271536]
  [1.49627824 1.68278522 1.97789551 1.43307757 1.56034266]
  [1.87006375 1.12807617 1.98858204 1.73596225 1.97478834]]

 [[1.88558356 1.47668682 1.85322208 1.14919383 1.28116717]
  [1.60724805 1.06046008 1.89034102 1.86540738 1.84929641]
  [1.42362393 1.63383577 1.90454446 1.95716396 1.74700037]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print(a_2)
print(d_2)

#d_2  is the sum from a_1 and c, this formula added 1 to all the elements in a_2, this happened becaused all elements in c were ones (1)

[[[83 14 19 42 60]
  [79 61 79 33 93]
  [88  6 74 25  4]]

 [[47 23 49  3 96]
  [46 92 30 84 97]
  [59 24 81 58 16]]]
[[[84. 15. 20. 43. 61.]
  [80. 62. 80. 34. 94.]
  [89.  7. 75. 26.  5.]]

 [[48. 24. 50.  4. 97.]
  [47. 93. 31. 85. 98.]
  [60. 25. 82. 59. 17.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
e = a_2 * c
print(e)

[[[83. 14. 19. 42. 60.]
  [79. 61. 79. 33. 93.]
  [88.  6. 74. 25.  4.]]

 [[47. 23. 49.  3. 96.]
  [46. 92. 30. 84. 97.]
  [59. 24. 81. 58. 16.]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [16]:
# your code/answer here
print(e.shape)
print(a_2.shape)
print(type(e))
print(type(a_2))

a_2 == e
#Yes, it's equal because it's just multipliying all values in a_2 for 1.

(2, 3, 5)
(2, 3, 5)
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [17]:
# your code here 
d_max = np.max(d_2)
d_min = np.min(d_2)
d_mean = np.mean(d_2)
print(d_max)
print(d_min)
print(d_mean)

98.0
4.0
53.166666666666664


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [18]:
# your code here
#print(d_2.shape)
f = np.empty((2,3,5))
print(f.shape)
print(f)

(2, 3, 5)


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [24]:
# your code here
print(d_2)
for group in d_2:
    #print(group)
    for array in group:
        #print(array)
        for value in array:
            #print(value)
            if d_min > value < d_mean:
                f[group][array][value] = 25
            if d_max < value > d_mean:
                f[group][array][value] = 75
            if value == d_mean:
                f[group][array][value] = 50
            if value == d_min:
                f[group][array][value] = 0
            if value == d_max:
                f[group][array][value] = 100
                
# f[d_2 <= d_min] = 0
# f[(d_2 > d_min)&(d_2 < d_mean)] = 25
# f[d_2 == d_mean] = 50
# f[(d_2 > d_mean)&(d_2 < d_max)] = 75
# f[d_2 >= d_max] = 100
print(f)

[[[84. 15. 20. 43. 61.]
  [80. 62. 80. 34. 94.]
  [89.  7. 75. 26.  5.]]

 [[48. 24. 50.  4. 97.]
  [47. 93. 31. 85. 98.]
  [60. 25. 82. 59. 17.]]]


IndexError: arrays used as indices must be of integer (or boolean) type

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here