# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [3]:
# your code here
print(np.__version__)

1.19.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [35]:
# Method 1
a = np.random.randint(1,100,(2,3,5))  
print("First array", a)

First array [[[57 40 37 41 31]
  [ 6 63 43  4 15]
  [64 34 50 30 45]]

 [[25 50  5 23 62]
  [86 96 87 96 24]
  [79 14 18  3 13]]]


In [36]:
# Method 2
rand_n2 = np.random.randn(2,3,5)  
print("Second array", rand_n2)

Second array [[[-0.29383537 -0.40018222  0.01604384 -0.12765738  0.23823358]
  [ 0.58425682 -1.15495173  0.40973542  1.47191425 -0.90703263]
  [ 0.98711739  0.17307121 -0.03086962  0.73677238  0.32890577]]

 [[ 1.82844105 -0.28359106  0.36331672 -0.42443398  0.92543891]
  [ 1.55828261  1.47758725 -1.7062003  -0.27995478 -1.83927772]
  [ 1.907237   -2.07187599 -0.97898447  2.57306578  0.1458064 ]]]


In [37]:
# Method 3
rand3 = np.random.rand(2,3,5) 
print("Third array", rand3)

Third array [[[0.79797463 0.39689781 0.74259864 0.33099122 0.50034638]
  [0.75060692 0.10916483 0.65855264 0.7815934  0.26504314]
  [0.94897228 0.17451164 0.75896153 0.16964775 0.2346206 ]]

 [[0.19887865 0.78939013 0.37071304 0.2782031  0.59152334]
  [0.26071213 0.58756894 0.18488725 0.2954958  0.40739487]
  [0.00821843 0.93463842 0.05896292 0.10716986 0.73795474]]]


#### 4. Print *a*.


In [38]:
# your code here
print(a)

[[[57 40 37 41 31]
  [ 6 63 43  4 15]
  [64 34 50 30 45]]

 [[25 50  5 23 62]
  [86 96 87 96 24]
  [79 14 18  3 13]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [39]:
# your code here
b=np.full((5,2,3), 1)
b_1=np.ones((5,2,3))

#### 6. Print *b*.


In [40]:
# your code here
print(b)
print(b_1)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [44]:
# your code here
print(np.size(a))
print(np.size(b))

30
30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [42]:
# your answer here
np.add(a,b)
#different shape

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [49]:
# your code here
c=np.reshape(b,(2,3,5))
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [50]:
# your code/answer here
d=a+c

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [54]:
# your code/answer here
print(a)
print( )
print(d)

[[[57 40 37 41 31]
  [ 6 63 43  4 15]
  [64 34 50 30 45]]

 [[25 50  5 23 62]
  [86 96 87 96 24]
  [79 14 18  3 13]]]

[[[58 41 38 42 32]
  [ 7 64 44  5 16]
  [65 35 51 31 46]]

 [[26 51  6 24 63]
  [87 97 88 97 25]
  [80 15 19  4 14]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [56]:
# your code here
e=a*c
e

array([[[57, 40, 37, 41, 31],
        [ 6, 63, 43,  4, 15],
        [64, 34, 50, 30, 45]],

       [[25, 50,  5, 23, 62],
        [86, 96, 87, 96, 24],
        [79, 14, 18,  3, 13]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [74]:
# your code/answer here
#es igual al ser c una matriz de unos

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [78]:
# your code here
d_max=np.max(d)
d_min=np.min(d)
d_mean=np.mean(d)
print(d_max)
print(d_min)
print(d_mean)

97
4
42.36666666666667


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [81]:
# your code here
f=np.empty([2,3,5])
f

array([[[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000, 6.94232143e-310],
        [1.16097020e-028, 6.37112413e-067, 2.73458899e-052,
         9.34427334e-067, 5.01163173e+217],
        [8.37170074e-144, 2.62090326e+180, 7.48389159e-067,
         5.88994857e-091, 1.10817876e-047]],

       [[5.01163116e+217, 5.49419094e-143, 9.80058441e+252,
         7.50189709e+247, 1.35617292e+248],
        [1.99786529e-076, 3.60966905e+174, 2.00620642e-052,
         1.25514652e-071, 3.30398637e+179],
        [5.04621361e+180, 8.37170571e-144, 9.30350598e+199,
         5.60230216e-067, 6.14415221e-144]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [83]:
# your code here
for i in d:
    for x in i:
        for y in x:
            if d_min<y & y<d_mean:
                f[i,x,y]=25
            elif d_mean<y & y<d_max:
                f[i,x,y]=75
            elif d_mean==y:
                f[i,x,y]=50
            elif d_min==y:
                f[i,x,y]=0
            elif d_max==y:
                f[i,x,y]=100

IndexError: index 58 is out of bounds for axis 2 with size 5

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [84]:
# your code here
print(d)
print(f)

[[[58 41 38 42 32]
  [ 7 64 44  5 16]
  [65 35 51 31 46]]

 [[26 51  6 24 63]
  [87 97 88 97 25]
  [80 15 19  4 14]]]
[[[0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
   6.94232143e-310]
  [1.16097020e-028 6.37112413e-067 2.73458899e-052 9.34427334e-067
   5.01163173e+217]
  [8.37170074e-144 2.62090326e+180 7.48389159e-067 5.88994857e-091
   1.10817876e-047]]

 [[5.01163116e+217 5.49419094e-143 9.80058441e+252 7.50189709e+247
   1.35617292e+248]
  [1.99786529e-076 3.60966905e+174 2.00620642e-052 1.25514652e-071
   3.30398637e+179]
  [5.04621361e+180 8.37170571e-144 9.30350598e+199 5.60230216e-067
   6.14415221e-144]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [86]:
# your code here
for i in d:
    for x in i:
        for y in x:
            if d_min<y & y<d_mean:
                f[i,x,y]="B"
            elif d_mean<y & y<d_max:
                f[i,x,y]="D"
            elif d_mean==y:
                f[i,x,y]="C"
            elif d_min==y:
                f[i,x,y]="A"
            elif d_max==y:
                f[i,x,y]="E"

IndexError: index 58 is out of bounds for axis 2 with size 5