# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
print(np.__version__)

1.19.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1: usign random.
a = np.random.random((2,3,5))
a

array([[[0.47075573, 0.31043655, 0.35257783, 0.6980163 , 0.63764418],
        [0.89139728, 0.7995838 , 0.77366709, 0.23945697, 0.87805168],
        [0.53608845, 0.3019588 , 0.56307961, 0.7255602 , 0.29174251]],

       [[0.34745422, 0.65030606, 0.47955149, 0.35512337, 0.3971777 ],
        [0.85681071, 0.53243629, 0.987244  , 0.35967375, 0.22312514],
        [0.25364724, 0.91169404, 0.07716353, 0.11628172, 0.90111458]]])

In [4]:
# Method 2: using Generator.integers
rng = np.random.default_rng()
rng.integers(100, size=(2,3,5))

array([[[76, 25, 47, 76, 16],
        [22, 74, 50, 23,  7],
        [16, 89, 80, 16,  4]],

       [[51, 41, 83, 93, 86],
        [76, 49, 95, 53, 70],
        [47, 72, 42,  7, 79]]])

In [5]:
# Method 3: using randint.
import random
np.random.randint(low=0, high=200, size=(2,3,5))

array([[[122,  86, 107,  80, 172],
        [137,  86,  78, 116, 172],
        [128, 107,  76,  98,  74]],

       [[ 68, 140, 121,  68,  42],
        [ 94, 152,  56,  73, 130],
        [121, 133, 105, 191,  53]]])

#### 4. Print *a*.


In [6]:
print(a)

[[[0.47075573 0.31043655 0.35257783 0.6980163  0.63764418]
  [0.89139728 0.7995838  0.77366709 0.23945697 0.87805168]
  [0.53608845 0.3019588  0.56307961 0.7255602  0.29174251]]

 [[0.34745422 0.65030606 0.47955149 0.35512337 0.3971777 ]
  [0.85681071 0.53243629 0.987244   0.35967375 0.22312514]
  [0.25364724 0.91169404 0.07716353 0.11628172 0.90111458]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
b = np.ones((5,2,3))

#### 6. Print *b*.


In [8]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
print(a.size)
print(b.size)

30
30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here: no, we can0t add a and b beacause they have different shapes.
np.add(a,b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here
c = np.reshape(b, (2, 3, 5))
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# now we can add a and c because they have the same shape. 
d = np.add(a,c)
d

array([[[1.47075573, 1.31043655, 1.35257783, 1.6980163 , 1.63764418],
        [1.89139728, 1.7995838 , 1.77366709, 1.23945697, 1.87805168],
        [1.53608845, 1.3019588 , 1.56307961, 1.7255602 , 1.29174251]],

       [[1.34745422, 1.65030606, 1.47955149, 1.35512337, 1.3971777 ],
        [1.85681071, 1.53243629, 1.987244  , 1.35967375, 1.22312514],
        [1.25364724, 1.91169404, 1.07716353, 1.11628172, 1.90111458]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# The difference between the values of a and d is 1, because the values of c were just ones. We have add this ones to the numbers in a.
print("This is a:\n", a)
print()
print("This is d:\n", d)

This is a:
 [[[0.47075573 0.31043655 0.35257783 0.6980163  0.63764418]
  [0.89139728 0.7995838  0.77366709 0.23945697 0.87805168]
  [0.53608845 0.3019588  0.56307961 0.7255602  0.29174251]]

 [[0.34745422 0.65030606 0.47955149 0.35512337 0.3971777 ]
  [0.85681071 0.53243629 0.987244   0.35967375 0.22312514]
  [0.25364724 0.91169404 0.07716353 0.11628172 0.90111458]]]

This is d:
 [[[1.47075573 1.31043655 1.35257783 1.6980163  1.63764418]
  [1.89139728 1.7995838  1.77366709 1.23945697 1.87805168]
  [1.53608845 1.3019588  1.56307961 1.7255602  1.29174251]]

 [[1.34745422 1.65030606 1.47955149 1.35512337 1.3971777 ]
  [1.85681071 1.53243629 1.987244   1.35967375 1.22312514]
  [1.25364724 1.91169404 1.07716353 1.11628172 1.90111458]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
e = np.multiply(a,c)
e

array([[[0.47075573, 0.31043655, 0.35257783, 0.6980163 , 0.63764418],
        [0.89139728, 0.7995838 , 0.77366709, 0.23945697, 0.87805168],
        [0.53608845, 0.3019588 , 0.56307961, 0.7255602 , 0.29174251]],

       [[0.34745422, 0.65030606, 0.47955149, 0.35512337, 0.3971777 ],
        [0.85681071, 0.53243629, 0.987244  , 0.35967375, 0.22312514],
        [0.25364724, 0.91169404, 0.07716353, 0.11628172, 0.90111458]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# a and e are the same because every positive number multiply by 1 is itself, so a = c * a.
print("This is a:\n", a)
print()
print("This is e:\n", e)

This is a:
 [[[0.47075573 0.31043655 0.35257783 0.6980163  0.63764418]
  [0.89139728 0.7995838  0.77366709 0.23945697 0.87805168]
  [0.53608845 0.3019588  0.56307961 0.7255602  0.29174251]]

 [[0.34745422 0.65030606 0.47955149 0.35512337 0.3971777 ]
  [0.85681071 0.53243629 0.987244   0.35967375 0.22312514]
  [0.25364724 0.91169404 0.07716353 0.11628172 0.90111458]]]

This is e:
 [[[0.47075573 0.31043655 0.35257783 0.6980163  0.63764418]
  [0.89139728 0.7995838  0.77366709 0.23945697 0.87805168]
  [0.53608845 0.3019588  0.56307961 0.7255602  0.29174251]]

 [[0.34745422 0.65030606 0.47955149 0.35512337 0.3971777 ]
  [0.85681071 0.53243629 0.987244   0.35967375 0.22312514]
  [0.25364724 0.91169404 0.07716353 0.11628172 0.90111458]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print("This is d:\n", d)
print()
print("Max value of d is:", d_max)
print()
print("Min value of d is:", d_min)
print()
print("The mean of d is:", d_mean)

This is d:
 [[[1.47075573 1.31043655 1.35257783 1.6980163  1.63764418]
  [1.89139728 1.7995838  1.77366709 1.23945697 1.87805168]
  [1.53608845 1.3019588  1.56307961 1.7255602  1.29174251]]

 [[1.34745422 1.65030606 1.47955149 1.35512337 1.3971777 ]
  [1.85681071 1.53243629 1.987244   1.35967375 1.22312514]
  [1.25364724 1.91169404 1.07716353 1.11628172 1.90111458]]]

Max value of d is: 1.987243999290218

Min value of d is: 1.0771635337520917

The mean of d is: 1.5306273606776093


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
f = np.empty((2,3,5))
print(f)
print()
print(d)

[[[1.47075573 1.31043655 1.35257783 1.6980163  1.63764418]
  [1.89139728 1.7995838  1.77366709 1.23945697 1.87805168]
  [1.53608845 1.3019588  1.56307961 1.7255602  1.29174251]]

 [[1.34745422 1.65030606 1.47955149 1.35512337 1.3971777 ]
  [1.85681071 1.53243629 1.987244   1.35967375 1.22312514]
  [1.25364724 1.91169404 1.07716353 1.11628172 1.90111458]]]

[[[1.47075573 1.31043655 1.35257783 1.6980163  1.63764418]
  [1.89139728 1.7995838  1.77366709 1.23945697 1.87805168]
  [1.53608845 1.3019588  1.56307961 1.7255602  1.29174251]]

 [[1.34745422 1.65030606 1.47955149 1.35512337 1.3971777 ]
  [1.85681071 1.53243629 1.987244   1.35967375 1.22312514]
  [1.25364724 1.91169404 1.07716353 1.11628172 1.90111458]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [62]:
#I am doing a for loop in order to iterate all the elements in my array. I use de len() method to iterate
#all the array. In this way I have a way to index each element in the array to use it later. Then I give
#them their new values. 

for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i, j])):
            
            value = d[i, j, k]
            
            if value > d_min and value < d_mean:
                f[i][j][k] = 25
        
            if value > d_mean and value < d_max:
                f[i][j][k] = 75
        
            if value == d_mean:
                f[i][j][k] = 50
        
            if value == d_min:
                f[i][j][k] = 0
        
            if value == d_max:
                f[i][j][k] = 100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [63]:
#Showing the results:
print(d)
print(f)

[[[1.4707557251427463 1.3104365506579807 1.352577825243059
   1.6980162984094052 1.637644178298934]
  [1.89139727661841 1.7995838022946469 1.7736670859164634
   1.2394569661238368 1.8780516846615796]
  [1.5360884462508464 1.3019588016585835 1.5630796122583015
   1.725560199576244 1.2917425133209544]]

 [[1.3474542239108054 1.650306064747888 1.4795514939906758
   1.3551233659716155 1.3971777034331905]
  [1.8568107086496901 1.5324362938614842 1.987243999290218
   1.3596737523980076 1.2231251426084364]
  [1.2536472363624427 1.911694042076224 1.0771635337520917
   1.1162817175697142 1.9011145752738106]]]
[[[ 25.  25.  25.  75.  75.]
  [ 75.  75.  75.  25.  75.]
  [ 75.  25.  75.  75.  25.]]

 [[ 25.  75.  25.  25.  25.]
  [ 75.  75. 100.  25.  25.]
  [ 25.  75.   0.  25.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [64]:
#First, I create a new empty array.
g = np.empty((2, 3, 5))

In [65]:
#Secondly, I change the accepted data in the array.
g = g.astype('object')

In [66]:
#Then I give it the letter to each index inside the array.
for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i,j])):
            
            value = d[i, j, k]
            
            if value > d_min and value < d_mean:
                g[i, j, k] = "A"
                
            if value > d_mean and value < d_max:
                g[i, j, k] = "B"
        
            if value == d_mean:
                g[i, j, k] = "C"
                
            if value == d_min:
                g[i, j, k] = "D"
        
            if value == d_max:
                g[i, j, k] = "E"      
                
print(g)

[[['A' 'A' 'A' 'B' 'B']
  ['B' 'B' 'B' 'A' 'B']
  ['B' 'A' 'B' 'B' 'A']]

 [['A' 'B' 'A' 'A' 'A']
  ['B' 'B' 'E' 'A' 'A']
  ['A' 'B' 'D' 'A' 'B']]]


In [11]:
#First, I create a function to check if a number is odd. 
def odd_number(num):
    return int(num) % 2 != 0

#Then, we change the number to string in order to be capable of to iterate it. With a for loop we check if there is odds numbers togethers.
#In that case, the function add a dash bewteen numbers and add 1 to the index, in order to check the next number.
def insert_dash(num):
    number_as_string = str(num)
    result = number_as_string[0]
    for i in range(1, len(number_as_string)):
        if odd_number(number_as_string[i - 1]) and odd_number(number_as_string[i]):
            result += "-"
        result += number_as_string[i]
    return result

insert_dash(32999345)

'329-9-9-345'

In [13]:
def color_probability(color, texture):
    if color == 'red' and texture == 'smooth':
        return '0.33'
    if  color == 'red' and texture == 'bumpy':
        return '0.57'
    if color == 'yellow' and texture == 'smooth':
        return '0.33'
    if color == 'yellow' and texture == 'bumpy':
        return '0.28'
    if color == 'green' and texture == 'smooth':
          return '0.33'
    if color == 'green' and texture == 'bumpy':
        return '0.14'
    
color_probability('red', 'bumpy')

'0.57'