# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
print(np.__version__)

1.19.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [11]:
# Method 1
a = np.random.random((2,3,5))
a

array([[[0.13117112, 0.11261683, 0.25210937, 0.13196677, 0.23308247],
        [0.72117414, 0.29428865, 0.77233765, 0.65898464, 0.74558773],
        [0.80004482, 0.2668996 , 0.92023948, 0.05002116, 0.816299  ]],

       [[0.26118954, 0.7226821 , 0.43506485, 0.45051214, 0.2656295 ],
        [0.51907417, 0.95256942, 0.0726878 , 0.97452108, 0.06195611],
        [0.38878497, 0.70098628, 0.05186584, 0.99463629, 0.44136152]]])

In [12]:
# Method 2
a = np.random.randint(low=0, high = 1000, size=(2,3,5))
a

array([[[119,  53, 585, 115,  14],
        [346, 947, 539, 623, 479],
        [436, 767, 823, 842, 976]],

       [[275, 145, 857, 175, 917],
        [598, 154, 201, 785, 483],
        [576, 864,  81, 660,  98]]])

In [13]:
# Method 3
a = np.random.rand(2,3,5)
a

array([[[0.58799383, 0.94344698, 0.35537359, 0.95990087, 0.78346253],
        [0.90149337, 0.98094064, 0.89247493, 0.33745147, 0.17904045],
        [0.96966198, 0.83791099, 0.58383679, 0.23779408, 0.2487782 ]],

       [[0.85180043, 0.86040496, 0.39150426, 0.83369407, 0.5669596 ],
        [0.53256106, 0.53298797, 0.65928068, 0.47969988, 0.70066503],
        [0.72292751, 0.25564088, 0.28209997, 0.54094476, 0.67889109]]])

#### 4. Print *a*.


In [14]:
a

array([[[0.58799383, 0.94344698, 0.35537359, 0.95990087, 0.78346253],
        [0.90149337, 0.98094064, 0.89247493, 0.33745147, 0.17904045],
        [0.96966198, 0.83791099, 0.58383679, 0.23779408, 0.2487782 ]],

       [[0.85180043, 0.86040496, 0.39150426, 0.83369407, 0.5669596 ],
        [0.53256106, 0.53298797, 0.65928068, 0.47969988, 0.70066503],
        [0.72292751, 0.25564088, 0.28209997, 0.54094476, 0.67889109]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [15]:
b = np.ones((5,2,3))

#### 6. Print *b*.


In [16]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [17]:
print(a.size)
print(b.size)
#yes, a and b have the same size (total count of elements in the array)

30
30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [19]:
np.concatenate((a, b))

#as the error says, to concatenate two awways they must have exactly the same dimensions, and this is not the case.
#but using np.append(a,b), it shows and unidimensional array with all the elements of both arrays.

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [23]:
c = np.reshape(b, (2,3,5))
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [25]:
d = np.concatenate((a, c))
d
#it works now because both arrays have the same shape

array([[[0.58799383, 0.94344698, 0.35537359, 0.95990087, 0.78346253],
        [0.90149337, 0.98094064, 0.89247493, 0.33745147, 0.17904045],
        [0.96966198, 0.83791099, 0.58383679, 0.23779408, 0.2487782 ]],

       [[0.85180043, 0.86040496, 0.39150426, 0.83369407, 0.5669596 ],
        [0.53256106, 0.53298797, 0.65928068, 0.47969988, 0.70066503],
        [0.72292751, 0.25564088, 0.28209997, 0.54094476, 0.67889109]],

       [[1.        , 1.        , 1.        , 1.        , 1.        ],
        [1.        , 1.        , 1.        , 1.        , 1.        ],
        [1.        , 1.        , 1.        , 1.        , 1.        ]],

       [[1.        , 1.        , 1.        , 1.        , 1.        ],
        [1.        , 1.        , 1.        , 1.        , 1.        ],
        [1.        , 1.        , 1.        , 1.        , 1.        ]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [27]:
print(a)
print(d)

[[[0.58799383 0.94344698 0.35537359 0.95990087 0.78346253]
  [0.90149337 0.98094064 0.89247493 0.33745147 0.17904045]
  [0.96966198 0.83791099 0.58383679 0.23779408 0.2487782 ]]

 [[0.85180043 0.86040496 0.39150426 0.83369407 0.5669596 ]
  [0.53256106 0.53298797 0.65928068 0.47969988 0.70066503]
  [0.72292751 0.25564088 0.28209997 0.54094476 0.67889109]]]
[[[0.58799383 0.94344698 0.35537359 0.95990087 0.78346253]
  [0.90149337 0.98094064 0.89247493 0.33745147 0.17904045]
  [0.96966198 0.83791099 0.58383679 0.23779408 0.2487782 ]]

 [[0.85180043 0.86040496 0.39150426 0.83369407 0.5669596 ]
  [0.53256106 0.53298797 0.65928068 0.47969988 0.70066503]
  [0.72292751 0.25564088 0.28209997 0.54094476 0.67889109]]

 [[1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]]

 [[1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.        

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [30]:
e = np.multiply(a,c)
e

array([[[0.58799383, 0.94344698, 0.35537359, 0.95990087, 0.78346253],
        [0.90149337, 0.98094064, 0.89247493, 0.33745147, 0.17904045],
        [0.96966198, 0.83791099, 0.58383679, 0.23779408, 0.2487782 ]],

       [[0.85180043, 0.86040496, 0.39150426, 0.83369407, 0.5669596 ],
        [0.53256106, 0.53298797, 0.65928068, 0.47969988, 0.70066503],
        [0.72292751, 0.25564088, 0.28209997, 0.54094476, 0.67889109]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
#e do equal to a because c is just an array with ones, so it just gives the same a array. 

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [64]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d, axis = 0)

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [68]:
f = np.empty([2,3,5])
f

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [69]:
for i in range(len(d)):
    for z in range(len(d[i])):
        for x in range(len(d[i][z])):
            if d_min in d:
                f[i][z][x] = 0
            elif d_max in d:
                f[i][z][x] = 100
            elif d_min < d[i][z][x] and d[i][z][x] < d_max:
                f[i][z][x] = 25
            elif d_mean < d[i][z][x] and d[i][z][x] < d_max:
                f[i][z][x] = 50
f

IndexError: index 2 is out of bounds for axis 0 with size 2

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here