# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [220]:
# your code here

import numpy as np

#### 2. Print your NumPy version.

In [221]:
# your code here

print(np.__version__)


1.19.4


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [222]:
# Method 1

a = np.random.random((2,3,5))

a

array([[[0.41876436, 0.50796352, 0.09184613, 0.1873685 , 0.86928603],
        [0.36370655, 0.38415284, 0.45521715, 0.59166781, 0.53998157],
        [0.80222552, 0.83877377, 0.62894386, 0.85594842, 0.8164326 ]],

       [[0.39004479, 0.99228163, 0.66821821, 0.56523042, 0.70132764],
        [0.79197178, 0.84908722, 0.53799334, 0.71713838, 0.48474854],
        [0.75350211, 0.69879525, 0.52404209, 0.43449284, 0.12822115]]])

In [223]:
# Method 2

np.random.randint(low=0, high=100, size=(2,3,5))

array([[[ 8, 62, 31, 38, 56],
        [94, 84, 39, 69, 49],
        [89, 49, 89, 58, 93]],

       [[38, 27, 99,  2, 40],
        [ 7, 57, 66, 44, 82],
        [39, 96, 18, 15, 16]]])

In [224]:
# Method 3

np.random.choice([0, 3], size = (2,3,5) ,p = [0.3,0.7])

array([[[3, 3, 3, 3, 3],
        [3, 3, 0, 3, 3],
        [0, 3, 3, 3, 0]],

       [[0, 3, 3, 3, 3],
        [3, 3, 0, 3, 3],
        [0, 3, 3, 0, 3]]])

#### 4. Print *a*.


In [225]:
# your code here

print(a)


[[[0.41876436 0.50796352 0.09184613 0.1873685  0.86928603]
  [0.36370655 0.38415284 0.45521715 0.59166781 0.53998157]
  [0.80222552 0.83877377 0.62894386 0.85594842 0.8164326 ]]

 [[0.39004479 0.99228163 0.66821821 0.56523042 0.70132764]
  [0.79197178 0.84908722 0.53799334 0.71713838 0.48474854]
  [0.75350211 0.69879525 0.52404209 0.43449284 0.12822115]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [226]:
# your code here

b = np.ones((5,2,3))


#### 6. Print *b*.


In [227]:
# your code here

print(b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [228]:
# your code here

if a.size == b.size:
    print(f'a and b have the same size: a = {a.size} and b = {b.size}')
else:
    print(f'a and b have not the same size: a= {a.size} b = {b.size}')


a and b have the same size: a = 30 and b = 30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [229]:
# your answer here

np.add(a,b)

# We can't add a to b because the arrays have not the same shape.

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [230]:
# your code here

c = b.reshape(2,3,5)

c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [231]:
# your code/answer here

d = np.add(a,c)

d

#They work because a and c have the same shape.

array([[[1.41876436, 1.50796352, 1.09184613, 1.1873685 , 1.86928603],
        [1.36370655, 1.38415284, 1.45521715, 1.59166781, 1.53998157],
        [1.80222552, 1.83877377, 1.62894386, 1.85594842, 1.8164326 ]],

       [[1.39004479, 1.99228163, 1.66821821, 1.56523042, 1.70132764],
        [1.79197178, 1.84908722, 1.53799334, 1.71713838, 1.48474854],
        [1.75350211, 1.69879525, 1.52404209, 1.43449284, 1.12822115]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [232]:
# your code/answer here

print(a)
print(d)

d - a 

# We have added the values of a into the first value of d. 
# The difference is 1.


[[[0.41876436 0.50796352 0.09184613 0.1873685  0.86928603]
  [0.36370655 0.38415284 0.45521715 0.59166781 0.53998157]
  [0.80222552 0.83877377 0.62894386 0.85594842 0.8164326 ]]

 [[0.39004479 0.99228163 0.66821821 0.56523042 0.70132764]
  [0.79197178 0.84908722 0.53799334 0.71713838 0.48474854]
  [0.75350211 0.69879525 0.52404209 0.43449284 0.12822115]]]
[[[1.41876436 1.50796352 1.09184613 1.1873685  1.86928603]
  [1.36370655 1.38415284 1.45521715 1.59166781 1.53998157]
  [1.80222552 1.83877377 1.62894386 1.85594842 1.8164326 ]]

 [[1.39004479 1.99228163 1.66821821 1.56523042 1.70132764]
  [1.79197178 1.84908722 1.53799334 1.71713838 1.48474854]
  [1.75350211 1.69879525 1.52404209 1.43449284 1.12822115]]]


array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [233]:
# your code here


e = a * c

e


array([[[0.41876436, 0.50796352, 0.09184613, 0.1873685 , 0.86928603],
        [0.36370655, 0.38415284, 0.45521715, 0.59166781, 0.53998157],
        [0.80222552, 0.83877377, 0.62894386, 0.85594842, 0.8164326 ]],

       [[0.39004479, 0.99228163, 0.66821821, 0.56523042, 0.70132764],
        [0.79197178, 0.84908722, 0.53799334, 0.71713838, 0.48474854],
        [0.75350211, 0.69879525, 0.52404209, 0.43449284, 0.12822115]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [234]:
# your code/answer here
    
print(a)
print(e)

# They are equal because when you multiple an array by 1 you got the same array. 

[[[0.41876436 0.50796352 0.09184613 0.1873685  0.86928603]
  [0.36370655 0.38415284 0.45521715 0.59166781 0.53998157]
  [0.80222552 0.83877377 0.62894386 0.85594842 0.8164326 ]]

 [[0.39004479 0.99228163 0.66821821 0.56523042 0.70132764]
  [0.79197178 0.84908722 0.53799334 0.71713838 0.48474854]
  [0.75350211 0.69879525 0.52404209 0.43449284 0.12822115]]]
[[[0.41876436 0.50796352 0.09184613 0.1873685  0.86928603]
  [0.36370655 0.38415284 0.45521715 0.59166781 0.53998157]
  [0.80222552 0.83877377 0.62894386 0.85594842 0.8164326 ]]

 [[0.39004479 0.99228163 0.66821821 0.56523042 0.70132764]
  [0.79197178 0.84908722 0.53799334 0.71713838 0.48474854]
  [0.75350211 0.69879525 0.52404209 0.43449284 0.12822115]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [235]:
# your code here

max_value = d.max()
min_value = d.min()
mean_value = d.mean()

print(d)

print(f'The max value of d is: {max_value}')
print(f'The min value of d is: {min_value}')
print(f'The mean value of d is: {mean_value}')


[[[1.41876436 1.50796352 1.09184613 1.1873685  1.86928603]
  [1.36370655 1.38415284 1.45521715 1.59166781 1.53998157]
  [1.80222552 1.83877377 1.62894386 1.85594842 1.8164326 ]]

 [[1.39004479 1.99228163 1.66821821 1.56523042 1.70132764]
  [1.79197178 1.84908722 1.53799334 1.71713838 1.48474854]
  [1.75350211 1.69879525 1.52404209 1.43449284 1.12822115]]]
The max value of d is: 1.9922816302409063
The min value of d is: 1.091846125538852
The mean value of d is: 1.5863124684170922


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [236]:
# your code here

f = np.empty([2,3,5]) 

f

array([[[1.41876436, 1.50796352, 1.09184613, 1.1873685 , 1.86928603],
        [1.36370655, 1.38415284, 1.45521715, 1.59166781, 1.53998157],
        [1.80222552, 1.83877377, 1.62894386, 1.85594842, 1.8164326 ]],

       [[1.39004479, 1.99228163, 1.66821821, 1.56523042, 1.70132764],
        [1.79197178, 1.84908722, 1.53799334, 1.71713838, 1.48474854],
        [1.75350211, 1.69879525, 1.52404209, 1.43449284, 1.12822115]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [318]:
# your code here

n = list(d)
h = list(f)



test = list(map(lambda x, y: y = 25 if (x > min_value and x < mean_value) else None, n,h))

#test = lambda x : True if (x > 10 and x < 20) else False       

# map(lambda x: 'lower' if x<3 else 'higher', lst)


print(test)


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
#   if (z > min_value) & (z < mean_value):
            n == 25
    
if (d[x] > min_value) and (d[x] < mean_value):
            f[y] = 25

if d > min_valu d and d < mean_value:
            
            
            
            
#            if d([element_1, element_2, element_3] > mean_value) and d([element_1, element_2, element_3] < max_value):
#                f([element_1, element_2, element_3]) = 75
#            if element_3 == mean_value: 
#                element == 50
#            if element_3 == min_value:
#                element == 0
#            if element_3 == max_value:
                         
                           

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

sdaf
asdf
asdf
sdf

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here