# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [6]:
import numpy as np

#### 2. Print your NumPy version.

In [7]:
np.version.version

'1.19.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [8]:
a = np.random.random((2,3,5))
a

array([[[0.42109963, 0.23884685, 0.08649638, 0.6651663 , 0.22564823],
        [0.4066931 , 0.29408913, 0.33260962, 0.29230964, 0.60899551],
        [0.93561639, 0.01486157, 0.4211266 , 0.74503066, 0.65612881]],

       [[0.57211054, 0.40728273, 0.93123244, 0.72555524, 0.81712632],
        [0.28814787, 0.80473389, 0.29533557, 0.02267542, 0.25252337],
        [0.91837813, 0.70849523, 0.58433556, 0.80773908, 0.85067267]]])

In [9]:
a2 = np.random.randint(low=0, high=100, size=(2,3,5))
a2

array([[[50, 80,  6, 43, 99],
        [52, 90,  6, 53, 69],
        [97, 38, 56, 61, 62]],

       [[34, 31, 43, 70, 76],
        [31, 96,  8, 17, 89],
        [58, 74, 98, 95, 13]]])

#### 4. Print *a*.


In [10]:
a

array([[[0.42109963, 0.23884685, 0.08649638, 0.6651663 , 0.22564823],
        [0.4066931 , 0.29408913, 0.33260962, 0.29230964, 0.60899551],
        [0.93561639, 0.01486157, 0.4211266 , 0.74503066, 0.65612881]],

       [[0.57211054, 0.40728273, 0.93123244, 0.72555524, 0.81712632],
        [0.28814787, 0.80473389, 0.29533557, 0.02267542, 0.25252337],
        [0.91837813, 0.70849523, 0.58433556, 0.80773908, 0.85067267]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [11]:
b = np.ones((5,2,3))

#### 6. Print *b*.


In [12]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [13]:
a.size

30

In [14]:
b.size

30

In [16]:
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [17]:
a + b
#Different shapes

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [18]:
c = np.reshape(b, (2, 3, 5))
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [19]:
d = a + c
d

array([[[1.42109963, 1.23884685, 1.08649638, 1.6651663 , 1.22564823],
        [1.4066931 , 1.29408913, 1.33260962, 1.29230964, 1.60899551],
        [1.93561639, 1.01486157, 1.4211266 , 1.74503066, 1.65612881]],

       [[1.57211054, 1.40728273, 1.93123244, 1.72555524, 1.81712632],
        [1.28814787, 1.80473389, 1.29533557, 1.02267542, 1.25252337],
        [1.91837813, 1.70849523, 1.58433556, 1.80773908, 1.85067267]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [20]:
a

array([[[0.42109963, 0.23884685, 0.08649638, 0.6651663 , 0.22564823],
        [0.4066931 , 0.29408913, 0.33260962, 0.29230964, 0.60899551],
        [0.93561639, 0.01486157, 0.4211266 , 0.74503066, 0.65612881]],

       [[0.57211054, 0.40728273, 0.93123244, 0.72555524, 0.81712632],
        [0.28814787, 0.80473389, 0.29533557, 0.02267542, 0.25252337],
        [0.91837813, 0.70849523, 0.58433556, 0.80773908, 0.85067267]]])

In [21]:
d

array([[[1.42109963, 1.23884685, 1.08649638, 1.6651663 , 1.22564823],
        [1.4066931 , 1.29408913, 1.33260962, 1.29230964, 1.60899551],
        [1.93561639, 1.01486157, 1.4211266 , 1.74503066, 1.65612881]],

       [[1.57211054, 1.40728273, 1.93123244, 1.72555524, 1.81712632],
        [1.28814787, 1.80473389, 1.29533557, 1.02267542, 1.25252337],
        [1.91837813, 1.70849523, 1.58433556, 1.80773908, 1.85067267]]])

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [22]:
e = a * c

#### 13. Does *e* equal to *a*? Why or why not?


In [23]:
e
#Yes, it is equal. We are just multiplying each element by one.

array([[[0.42109963, 0.23884685, 0.08649638, 0.6651663 , 0.22564823],
        [0.4066931 , 0.29408913, 0.33260962, 0.29230964, 0.60899551],
        [0.93561639, 0.01486157, 0.4211266 , 0.74503066, 0.65612881]],

       [[0.57211054, 0.40728273, 0.93123244, 0.72555524, 0.81712632],
        [0.28814787, 0.80473389, 0.29533557, 0.02267542, 0.25252337],
        [0.91837813, 0.70849523, 0.58433556, 0.80773908, 0.85067267]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [24]:
d

array([[[1.42109963, 1.23884685, 1.08649638, 1.6651663 , 1.22564823],
        [1.4066931 , 1.29408913, 1.33260962, 1.29230964, 1.60899551],
        [1.93561639, 1.01486157, 1.4211266 , 1.74503066, 1.65612881]],

       [[1.57211054, 1.40728273, 1.93123244, 1.72555524, 1.81712632],
        [1.28814787, 1.80473389, 1.29533557, 1.02267542, 1.25252337],
        [1.91837813, 1.70849523, 1.58433556, 1.80773908, 1.85067267]]])

In [25]:
d_max = np.max(d)
d_max

1.9356163916239202

In [26]:
d_min = np.min(d)
d_min

1.0148615678682111

In [27]:
d_mean = np.mean(d)
d_mean

1.5110354156152073

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [28]:
f = np.empty((2,3,5))


In [29]:
f

array([[[1.42109963, 1.23884685, 1.08649638, 1.6651663 , 1.22564823],
        [1.4066931 , 1.29408913, 1.33260962, 1.29230964, 1.60899551],
        [1.93561639, 1.01486157, 1.4211266 , 1.74503066, 1.65612881]],

       [[1.57211054, 1.40728273, 1.93123244, 1.72555524, 1.81712632],
        [1.28814787, 1.80473389, 1.29533557, 1.02267542, 1.25252337],
        [1.91837813, 1.70849523, 1.58433556, 1.80773908, 1.85067267]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [30]:
solut = f.reshape(f.size)


for i in range(d.size):
    
    if d_min < d.reshape(d.size)[i] < d_mean:
         solut [i] = 25
            
    elif d_mean < d.reshape(d.size)[i] < d_max:
         solut [i] = 75
            
    elif d.reshape(d.size)[i] == d_mean:
         solut [i] = 50
                    
    elif d.reshape(d.size)[i] == d_min:
         solut [i] = 0
            
    elif d.reshape(d.size)[i] == d_max:
          solut [i] = 100
            
    f = solut.reshape(2,3,5)
    
print(f)

[[[ 25.  25.  25.  75.  25.]
  [ 25.  25.  25.  25.  75.]
  [100.   0.  25.  75.  75.]]

 [[ 75.  25.  75.  75.  75.]
  [ 25.  75.  25.  25.  25.]
  [ 75.  75.  75.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.