# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [67]:
# your code here
!pip install numpy
import numpy as np

In [68]:
#### 2. Print your NumPy version.

In [69]:
# your code here
print(np.__version__)

1.19.4


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [90]:
# Method 1
a = np.random.random((2,3,5))

In [89]:
# Method 2
a = np.random.randint(100,size=(2,3,5))

In [72]:
# Method 3
a = np.random.randn(2,3,5)

#### 4. Print *a*.


In [91]:
# your code here
print(a)

[[[0.81911366 0.30429859 0.16747165 0.90994618 0.77843452]
  [0.78564322 0.28016599 0.35922423 0.16123178 0.82991301]
  [0.85432529 0.54953154 0.45260042 0.52193518 0.67342401]]

 [[0.98831368 0.49608597 0.12878684 0.54073033 0.63928843]
  [0.26898109 0.12092087 0.85690371 0.49380182 0.87790852]
  [0.11841217 0.74340315 0.55947311 0.75075262 0.48884073]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [92]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [93]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [94]:
# your code here
if a.size == b.size:
    print("True")

True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [95]:
# your answer here
if a.shape != b.shape:
    print("a and b do not have the same shape")
else:
    print("a and b have the same shape")
    print(a+b)

a and b do not have the same shape


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [96]:
# your code here
c = np.reshape(b, (2,3,5))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [97]:
# your code/answer here
d = a + c

if a.shape != c.shape:
    print("a and c do not have the same shape")
else:
    print("a and c have the same shape")
    print(a + c)

a and c have the same shape
[[[1.81911366 1.30429859 1.16747165 1.90994618 1.77843452]
  [1.78564322 1.28016599 1.35922423 1.16123178 1.82991301]
  [1.85432529 1.54953154 1.45260042 1.52193518 1.67342401]]

 [[1.98831368 1.49608597 1.12878684 1.54073033 1.63928843]
  [1.26898109 1.12092087 1.85690371 1.49380182 1.87790852]
  [1.11841217 1.74340315 1.55947311 1.75075262 1.48884073]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [99]:
# your code/answer here
print(a)
print(d)
print("Values in d are values in a + 1")

[[[0.81911366 0.30429859 0.16747165 0.90994618 0.77843452]
  [0.78564322 0.28016599 0.35922423 0.16123178 0.82991301]
  [0.85432529 0.54953154 0.45260042 0.52193518 0.67342401]]

 [[0.98831368 0.49608597 0.12878684 0.54073033 0.63928843]
  [0.26898109 0.12092087 0.85690371 0.49380182 0.87790852]
  [0.11841217 0.74340315 0.55947311 0.75075262 0.48884073]]]
[[[1.81911366 1.30429859 1.16747165 1.90994618 1.77843452]
  [1.78564322 1.28016599 1.35922423 1.16123178 1.82991301]
  [1.85432529 1.54953154 1.45260042 1.52193518 1.67342401]]

 [[1.98831368 1.49608597 1.12878684 1.54073033 1.63928843]
  [1.26898109 1.12092087 1.85690371 1.49380182 1.87790852]
  [1.11841217 1.74340315 1.55947311 1.75075262 1.48884073]]]
Values in d are values in a + 1


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [100]:
# your code here
e = a * c
print(e)

[[[0.81911366 0.30429859 0.16747165 0.90994618 0.77843452]
  [0.78564322 0.28016599 0.35922423 0.16123178 0.82991301]
  [0.85432529 0.54953154 0.45260042 0.52193518 0.67342401]]

 [[0.98831368 0.49608597 0.12878684 0.54073033 0.63928843]
  [0.26898109 0.12092087 0.85690371 0.49380182 0.87790852]
  [0.11841217 0.74340315 0.55947311 0.75075262 0.48884073]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [101]:
# your code/answer here
if a.all() == e.all():
    print("Any number multiplied by 1 stays the same")

Any number multiplied by 1 stays the same


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [102]:
# your code here
d_max = np.amax(d)
d_min = np.amin(d)
d_mean = np.mean(d)

print(d_max)
print(d_min)
print(d_mean)

1.9883136797862622
1.1184121708934556
1.550662076943747


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [103]:
# your code here
f = np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [104]:
# your code here

for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
           
            if d[i][j][k] == d_mean:
                f[i][j][k] = 50.0
            if d[i][j][k] == d_min:
                f[i][j][k] = 0.0
            if d[i][j][k] == d_max:
                f[i][j][k] = 100.0
            if d[i][j][k] > d_min and d[i][j][k] < d_mean:
                f[i][j][k] = 25.0
            if d[i][j][k] > d_mean and d[i][j][k] < d_max:
                f[i][j][k] = 75.0
          
print(f)
    

[[[ 75.  25.  25.  75.  75.]
  [ 75.  25.  25.  25.  75.]
  [ 75.  25.  25.  25.  75.]]

 [[100.  25.  25.  25.  75.]
  [ 25.  25.  75.  25.  75.]
  [  0.  75.  75.  75.  25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [105]:
# your code here
print(d)

print(f)

[[[1.81911366 1.30429859 1.16747165 1.90994618 1.77843452]
  [1.78564322 1.28016599 1.35922423 1.16123178 1.82991301]
  [1.85432529 1.54953154 1.45260042 1.52193518 1.67342401]]

 [[1.98831368 1.49608597 1.12878684 1.54073033 1.63928843]
  [1.26898109 1.12092087 1.85690371 1.49380182 1.87790852]
  [1.11841217 1.74340315 1.55947311 1.75075262 1.48884073]]]
[[[ 75.  25.  25.  75.  75.]
  [ 75.  25.  25.  25.  75.]
  [ 75.  25.  25.  25.  75.]]

 [[100.  25.  25.  25.  75.]
  [ 25.  25.  75.  25.  75.]
  [  0.  75.  75.  75.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [129]:
# your code here

#A new array "g" is created not using np, thus it will not have the type int implicit.
    
g = [[[[] for p in range(5)] for q in range(3)] for r in range(2)]

            
for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
           
            if d[i][j][k] == d_mean:
                g[i][j][k] = 'C'
            if d[i][j][k] == d_min:
                g[i][j][k] = 'A'
            if d[i][j][k] == d_max:
                g[i][j][k] = 'E'
            if d[i][j][k] > d_min and d[i][j][k] < d_mean:
                g[i][j][k] = 'B'
            if d[i][j][k] > d_mean and d[i][j][k] < d_max:
                g[i][j][k] = 'D'
                
g

[[['D', 'B', 'B', 'D', 'D'],
  ['D', 'B', 'B', 'B', 'D'],
  ['D', 'B', 'B', 'B', 'D']],
 [['E', 'B', 'B', 'B', 'D'],
  ['B', 'B', 'D', 'B', 'D'],
  ['A', 'D', 'D', 'D', 'B']]]