# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here

import numpy as np


#### 2. Print your NumPy version.

In [2]:
# your code here

np.version.version


'1.19.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1

a = np.random.random((2,3,5))
print(a)

[[[0.72997156 0.7631853  0.14571398 0.29552149 0.40227241]
  [0.79922075 0.86358912 0.67755889 0.15987876 0.48342242]
  [0.55311327 0.2698515  0.61122437 0.25602924 0.17941333]]

 [[0.51394409 0.66309326 0.00600232 0.29403448 0.4727501 ]
  [0.94522346 0.3054267  0.65774039 0.67450931 0.38183618]
  [0.58481961 0.21324272 0.71087869 0.18674066 0.30685479]]]


In [4]:
# Method 2

a2 = np.random.rand(2,3,5)
print(a2)

[[[0.75517498 0.95096292 0.41676128 0.12971403 0.0543523 ]
  [0.52627833 0.83167008 0.64355804 0.00776523 0.71098818]
  [0.2374156  0.43559605 0.77724716 0.05568116 0.54348806]]

 [[0.04737813 0.34674833 0.09732132 0.26680724 0.78279363]
  [0.11226227 0.81440045 0.27435238 0.60138686 0.2009633 ]
  [0.82849155 0.92022714 0.73306261 0.2905624  0.18428377]]]


In [5]:
# Method 3

a3 = np.random.ranf((2,3,5))


#### 4. Print *a*.


In [6]:
# your code here
print(a)


[[[0.72997156 0.7631853  0.14571398 0.29552149 0.40227241]
  [0.79922075 0.86358912 0.67755889 0.15987876 0.48342242]
  [0.55311327 0.2698515  0.61122437 0.25602924 0.17941333]]

 [[0.51394409 0.66309326 0.00600232 0.29403448 0.4727501 ]
  [0.94522346 0.3054267  0.65774039 0.67450931 0.38183618]
  [0.58481961 0.21324272 0.71087869 0.18674066 0.30685479]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here

b = np.ones((5,2,3))

#### 6. Print *b*.


In [8]:
# your code here

print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here

a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here

print(np.add(a, b))

### I cannot add a to b since they have different shapes

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here

c = np.reshape(b, (2,3,5))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here

d = np.add(a, c)
print(d)

### Add procedure works now because both, a and c have the same shape.

[[[1.72997156 1.7631853  1.14571398 1.29552149 1.40227241]
  [1.79922075 1.86358912 1.67755889 1.15987876 1.48342242]
  [1.55311327 1.2698515  1.61122437 1.25602924 1.17941333]]

 [[1.51394409 1.66309326 1.00600232 1.29403448 1.4727501 ]
  [1.94522346 1.3054267  1.65774039 1.67450931 1.38183618]
  [1.58481961 1.21324272 1.71087869 1.18674066 1.30685479]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here

print(a)
print('\n')
print(d)

### a and d arrays have the same shape and they share the same floating figures, c has added 
### an "1.0" from b to all its elements.

[[[0.72997156 0.7631853  0.14571398 0.29552149 0.40227241]
  [0.79922075 0.86358912 0.67755889 0.15987876 0.48342242]
  [0.55311327 0.2698515  0.61122437 0.25602924 0.17941333]]

 [[0.51394409 0.66309326 0.00600232 0.29403448 0.4727501 ]
  [0.94522346 0.3054267  0.65774039 0.67450931 0.38183618]
  [0.58481961 0.21324272 0.71087869 0.18674066 0.30685479]]]


[[[1.72997156 1.7631853  1.14571398 1.29552149 1.40227241]
  [1.79922075 1.86358912 1.67755889 1.15987876 1.48342242]
  [1.55311327 1.2698515  1.61122437 1.25602924 1.17941333]]

 [[1.51394409 1.66309326 1.00600232 1.29403448 1.4727501 ]
  [1.94522346 1.3054267  1.65774039 1.67450931 1.38183618]
  [1.58481961 1.21324272 1.71087869 1.18674066 1.30685479]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here

e = np.multiply(a, c)
print(e)

[[[0.72997156 0.7631853  0.14571398 0.29552149 0.40227241]
  [0.79922075 0.86358912 0.67755889 0.15987876 0.48342242]
  [0.55311327 0.2698515  0.61122437 0.25602924 0.17941333]]

 [[0.51394409 0.66309326 0.00600232 0.29403448 0.4727501 ]
  [0.94522346 0.3054267  0.65774039 0.67450931 0.38183618]
  [0.58481961 0.21324272 0.71087869 0.18674066 0.30685479]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here

a == e

### All the elements between both arrays are equal. It makes sense, every element from a has been multiplied by 1. 


array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here

d_max=np.max(d)
d_min=np.min(d)
d_mean=np.mean(d)

print(f'From array d, the maximum is', d_max , ', minimum is' , d_min , 'and mean is' , d_mean , '.')

From array d, the maximum is 1.9452234564650115 , minimum is 1.0060023224190222 and mean is 1.4702354392634787 .


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here

f = np.empty((2,3,5))


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [20]:
# your code here

### Let's generate it by using some loops:
a=0
for x in d:
    b=0
    for y in x:
        c=0
        for z in y :
            if z == d_min:
                f[a,b,c] = 0
            elif z < d_mean:
                f[a,b,c] = 25
            elif z == d_mean:
                f[a,b,c] = 50
            elif z < d_max:
                f[a,b,c] = 75
            else:
                f[a,b,c] = 100
            c=c+1
        b=b+1
    a=a+1
    

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [21]:
# your code here
print(d)
print(f)

### Yes, everything seems to be fine :) . 

[[[1.72997156 1.7631853  1.14571398 1.29552149 1.40227241]
  [1.79922075 1.86358912 1.67755889 1.15987876 1.48342242]
  [1.55311327 1.2698515  1.61122437 1.25602924 1.17941333]]

 [[1.51394409 1.66309326 1.00600232 1.29403448 1.4727501 ]
  [1.94522346 1.3054267  1.65774039 1.67450931 1.38183618]
  [1.58481961 1.21324272 1.71087869 1.18674066 1.30685479]]]
[[[ 75.  75.  25.  25.  25.]
  [ 75.  75.  75.  25.  75.]
  [ 75.  25.  75.  25.  25.]]

 [[ 75.  75.   0.  25.  75.]
  [100.  25.  75.  75.  25.]
  [ 75.  25.  75.  25.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here