# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
# your code here
import numpy as np


#### 2. Print your NumPy version.

In [3]:
# your code here
print(np.__version__)


1.19.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [10]:
# Method 1
a = np.random.random((2,3,5))
print (a)
print (a.shape)
print (a.size)

[[[0.91818372 0.33864079 0.471463   0.33860388 0.97846364]
  [0.16730546 0.70711836 0.85729464 0.01641246 0.15238159]
  [0.19704374 0.37253084 0.44520584 0.63911181 0.98203575]]

 [[0.64552013 0.68650296 0.73332616 0.97046827 0.23310738]
  [0.16572285 0.54249169 0.91661927 0.70191665 0.97904709]
  [0.55538141 0.94773862 0.96184381 0.05617789 0.27293974]]]
(2, 3, 5)
30


In [13]:
# Method 2
a = np.random.randn(2,3,5)
print(a)

[[[ 0.24041261 -0.6264484  -0.59649429 -0.05370901 -0.06940104]
  [-0.98743829  1.28212479 -0.24538258  1.52837982  0.51971368]
  [-0.02328816 -0.79872632  1.08870885 -0.41128948 -0.03039377]]

 [[ 0.96882166  0.27366369  0.44930492  1.18249545  0.41156917]
  [ 0.63159646 -0.57945012 -0.45671814  0.98403723  1.01174048]
  [ 0.00374038 -0.48653893  0.15118878 -0.72497887 -2.12742896]]]


In [9]:
# Method 3
a = np.random.randint(100,size = (2,3,5))
print(a)

[[[31 23 25 43 50]
  [36 35 48 55 95]
  [66 86 53 97 33]]

 [[19 98 88 92 84]
  [61 95 75 81 19]
  [34 98 59 18 51]]]


#### 4. Print *a*.


In [22]:
# your code here
print(a)

[[[0.16651117 0.37567534 0.77013528 0.20455137 0.23927578]
  [0.81999466 0.87152735 0.22825882 0.58096492 0.06728321]
  [0.90828533 0.40433921 0.04675609 0.23835383 0.21011   ]]

 [[0.22960927 0.09631814 0.63318043 0.6883518  0.13386789]
  [0.82921542 0.99229408 0.45210974 0.90236013 0.9089321 ]
  [0.35639193 0.42108214 0.89411657 0.11113562 0.15321964]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [11]:
# your code here
b = np.ones((5,2,3))


#### 6. Print *b*.


In [35]:
# your code here
print(b)
print( b.size)
print(b.shape)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
30
(5, 2, 3)


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [31]:
# your code here
if a.size == b.size:
        print("True")

True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [38]:
# your answer here
c = np.add(a,b)
# a and b do not have the same shape, so it is not possible to add them.

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [12]:
# your code here
print (b.shape)
c = b.transpose(1,2,0)

print(c.shape)

(5, 2, 3)
(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [16]:
# your code/answer here
d = np.add(a,c)
print(d)
print(d.shape)
#It works because both arrays have the same shape

[[[1.91818372 1.33864079 1.471463   1.33860388 1.97846364]
  [1.16730546 1.70711836 1.85729464 1.01641246 1.15238159]
  [1.19704374 1.37253084 1.44520584 1.63911181 1.98203575]]

 [[1.64552013 1.68650296 1.73332616 1.97046827 1.23310738]
  [1.16572285 1.54249169 1.91661927 1.70191665 1.97904709]
  [1.55538141 1.94773862 1.96184381 1.05617789 1.27293974]]]
(2, 3, 5)


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [17]:
# your code/answer here
print(a)

print(d)
# a and b are 2x3x5 3-dimensional arrays but in a, all values are equaled to 0 and in b, all values are equaled to 1

[[[0.91818372 0.33864079 0.471463   0.33860388 0.97846364]
  [0.16730546 0.70711836 0.85729464 0.01641246 0.15238159]
  [0.19704374 0.37253084 0.44520584 0.63911181 0.98203575]]

 [[0.64552013 0.68650296 0.73332616 0.97046827 0.23310738]
  [0.16572285 0.54249169 0.91661927 0.70191665 0.97904709]
  [0.55538141 0.94773862 0.96184381 0.05617789 0.27293974]]]
[[[1.91818372 1.33864079 1.471463   1.33860388 1.97846364]
  [1.16730546 1.70711836 1.85729464 1.01641246 1.15238159]
  [1.19704374 1.37253084 1.44520584 1.63911181 1.98203575]]

 [[1.64552013 1.68650296 1.73332616 1.97046827 1.23310738]
  [1.16572285 1.54249169 1.91661927 1.70191665 1.97904709]
  [1.55538141 1.94773862 1.96184381 1.05617789 1.27293974]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [18]:
# your code here
e = np.multiply(a,d)
print(e)

[[[1.76124505 0.45331838 0.69374036 0.45325647 1.93585472]
  [0.19529657 1.20713472 1.59224873 0.01668183 0.17560174]
  [0.23586997 0.51131006 0.64341408 1.04757572 1.94642997]]

 [[1.06221638 1.15778928 1.27109341 1.91227693 0.28744643]
  [0.19318691 0.83678893 1.75681015 1.19460364 1.93758029]
  [0.86382993 1.84594711 1.88698733 0.05933384 0.34743584]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [21]:
# your code/answer here
if e.all() == a.all():
    print("True")
else:
    print("False")

True


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [24]:
# your code here
d_max = np.amax(d)
d_min = np.amin(d)
d_mean = np.mean(d)
print(d_max)
print(d_min)
print(d_mean)

1.9820357533144577
1.0164124597594415
1.5650199811185257


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [28]:
# your code here
f = np.empty([2,3,5])
print(f)
print(f.shape)

[[[1.76124505 0.45331838 0.69374036 0.45325647 1.93585472]
  [0.19529657 1.20713472 1.59224873 0.01668183 0.17560174]
  [0.23586997 0.51131006 0.64341408 1.04757572 1.94642997]]

 [[1.06221638 1.15778928 1.27109341 1.91227693 0.28744643]
  [0.19318691 0.83678893 1.75681015 1.19460364 1.93758029]
  [0.86382993 1.84594711 1.88698733 0.05933384 0.34743584]]]
(2, 3, 5)


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [1]:
# your code here
for i in f:
    if x in d > d_min and < d_mean:
        f.append

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here