# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [11]:
import numpy as np

#### 2. Print your NumPy version.

In [12]:
print(np.__version__)

1.19.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [13]:
# Method 1
a=np.random.randint(low=0, high=100, size=(2,3,5))
a

array([[[23, 30, 75, 64, 12],
        [80, 31, 26, 12, 34],
        [96, 68, 87, 67, 16]],

       [[71, 35, 43, 15, 97],
        [33, 28, 51,  4,  0],
        [81, 56, 77,  4, 97]]])

In [14]:
# Method 2
a = np.random.random((2,3,5))
a


array([[[0.07810454, 0.49336644, 0.52807273, 0.4686857 , 0.30219068],
        [0.6819912 , 0.41909075, 0.89326787, 0.37928588, 0.71433187],
        [0.043805  , 0.26001245, 0.50852922, 0.62906234, 0.56445987]],

       [[0.66587348, 0.44301826, 0.77721475, 0.94777405, 0.48435542],
        [0.21309093, 0.88923904, 0.26517672, 0.51943771, 0.00691245],
        [0.13616963, 0.15913127, 0.45762789, 0.03586301, 0.58317922]]])

In [15]:
# Method 3
a = np.random.random_sample((2,3,5))
a

array([[[0.7613611 , 0.01520981, 0.30482162, 0.78697458, 0.42117747],
        [0.39963297, 0.79693741, 0.13473048, 0.56763622, 0.18935611],
        [0.15926857, 0.62997733, 0.99772113, 0.51735687, 0.72573368]],

       [[0.97883557, 0.28570213, 0.49813636, 0.74919441, 0.00274378],
        [0.77950975, 0.09974782, 0.52282152, 0.97688647, 0.87072726],
        [0.26222956, 0.10454977, 0.01068817, 0.72281022, 0.71591476]]])

#### 4. Print *a*.


In [16]:
a

array([[[0.7613611 , 0.01520981, 0.30482162, 0.78697458, 0.42117747],
        [0.39963297, 0.79693741, 0.13473048, 0.56763622, 0.18935611],
        [0.15926857, 0.62997733, 0.99772113, 0.51735687, 0.72573368]],

       [[0.97883557, 0.28570213, 0.49813636, 0.74919441, 0.00274378],
        [0.77950975, 0.09974782, 0.52282152, 0.97688647, 0.87072726],
        [0.26222956, 0.10454977, 0.01068817, 0.72281022, 0.71591476]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [17]:
# your code here
b=np.ones((5,2,3))

#### 6. Print *b*.


In [18]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [19]:
print(np.size(a))
print(np.size(b))

# your code here

30
30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [20]:
# your answer here
np.add(a,b)
# No es posible, a tiene distinta forma que b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [21]:
# your code here
c=np.reshape(b, (2, 3, 5))
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [22]:
d=np.add(a,c)
d

array([[[1.7613611 , 1.01520981, 1.30482162, 1.78697458, 1.42117747],
        [1.39963297, 1.79693741, 1.13473048, 1.56763622, 1.18935611],
        [1.15926857, 1.62997733, 1.99772113, 1.51735687, 1.72573368]],

       [[1.97883557, 1.28570213, 1.49813636, 1.74919441, 1.00274378],
        [1.77950975, 1.09974782, 1.52282152, 1.97688647, 1.87072726],
        [1.26222956, 1.10454977, 1.01068817, 1.72281022, 1.71591476]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [23]:
print(a)
print()
print(d)# your code/answer here

# Si han sumado las matrices (a y c)

[[[0.7613611  0.01520981 0.30482162 0.78697458 0.42117747]
  [0.39963297 0.79693741 0.13473048 0.56763622 0.18935611]
  [0.15926857 0.62997733 0.99772113 0.51735687 0.72573368]]

 [[0.97883557 0.28570213 0.49813636 0.74919441 0.00274378]
  [0.77950975 0.09974782 0.52282152 0.97688647 0.87072726]
  [0.26222956 0.10454977 0.01068817 0.72281022 0.71591476]]]

[[[1.7613611  1.01520981 1.30482162 1.78697458 1.42117747]
  [1.39963297 1.79693741 1.13473048 1.56763622 1.18935611]
  [1.15926857 1.62997733 1.99772113 1.51735687 1.72573368]]

 [[1.97883557 1.28570213 1.49813636 1.74919441 1.00274378]
  [1.77950975 1.09974782 1.52282152 1.97688647 1.87072726]
  [1.26222956 1.10454977 1.01068817 1.72281022 1.71591476]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [24]:
# your code here
e=np.multiply(a,c)


#### 13. Does *e* equal to *a*? Why or why not?


In [25]:
print(e)
print()
print(a)
# "a" es igual que "e" porque "c" son 2 matricies de 1 y por eso da lo mismo.

[[[0.7613611  0.01520981 0.30482162 0.78697458 0.42117747]
  [0.39963297 0.79693741 0.13473048 0.56763622 0.18935611]
  [0.15926857 0.62997733 0.99772113 0.51735687 0.72573368]]

 [[0.97883557 0.28570213 0.49813636 0.74919441 0.00274378]
  [0.77950975 0.09974782 0.52282152 0.97688647 0.87072726]
  [0.26222956 0.10454977 0.01068817 0.72281022 0.71591476]]]

[[[0.7613611  0.01520981 0.30482162 0.78697458 0.42117747]
  [0.39963297 0.79693741 0.13473048 0.56763622 0.18935611]
  [0.15926857 0.62997733 0.99772113 0.51735687 0.72573368]]

 [[0.97883557 0.28570213 0.49813636 0.74919441 0.00274378]
  [0.77950975 0.09974782 0.52282152 0.97688647 0.87072726]
  [0.26222956 0.10454977 0.01068817 0.72281022 0.71591476]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [26]:
# your code here
d_max=np.amax(d)
print(d_max)
d_min=np.amin(d)
print(d_min)
d_mean=np.mean(d)
print(d_mean)

1.997721132831555
1.002743778402655
1.499613096558963


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [47]:
# your code here
f=np.empty_like(d)*0

print(d[1][1][1])
print(d)
d_max=np.amax(d)
print(d_max)
d_min=np.amin(d)
print(d_min)
d_mean=np.mean(d)
print(d_mean)

1.0997478247269474
[[[1.7613611  1.01520981 1.30482162 1.78697458 1.42117747]
  [1.39963297 1.79693741 1.13473048 1.56763622 1.18935611]
  [1.15926857 1.62997733 1.99772113 1.51735687 1.72573368]]

 [[1.97883557 1.28570213 1.49813636 1.74919441 1.00274378]
  [1.77950975 1.09974782 1.52282152 1.97688647 1.87072726]
  [1.26222956 1.10454977 1.01068817 1.72281022 1.71591476]]]
1.997721132831555
1.002743778402655
1.499613096558963


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [48]:
# your code here
for i in range(len(d)):
    for e in range(len(d[i])):
        for a in range(len(d[i][e])):
            if d_min == d[i][e][a]:
                f[i][e][a]=0
            if d_max == d[i][e][a]:
                f[i][e][a]=100
            if d_mean == d[i][e][a]:
                f[i][e][a]=50
            if d_min < d[i][e][a] and d[i][e][a] < d_max:
                f[i][e][a]=25
            if d_mean < d[i][e][a] and d[i][e][a] < d_max:
                f[i][e][a]=75
f 

array([[[ 75.,  25.,  25.,  75.,  25.],
        [ 25.,  75.,  25.,  75.,  25.],
        [ 25.,  75., 100.,  75.,  75.]],

       [[ 75.,  25.,  25.,  75.,   0.],
        [ 75.,  25.,  75.,  75.,  75.],
        [ 25.,  25.,  25.,  75.,  75.]]])

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [49]:
f = f.astype('object') # esto permite que se cambie la matriz.

In [50]:
for i in range(len(f)):
    for e in range(len(f[i])):
        for a in range(len(f[i][e])):
            if 0 == f[i][e][a]:
                f[i][e][a]='A'
            if 25 == f[i][e][a]:
                f[i][e][a]= 'B'
            if 50 == f[i][e][a]:
                f[i][e][a]='C'
            if 75 == f[i][e][a]:
                f[i][e][a]='D'
            if 100 == f[i][e][a]:
                f[i][e][a]='E'

In [51]:
f

array([[['D', 'B', 'B', 'D', 'B'],
        ['B', 'D', 'B', 'D', 'B'],
        ['B', 'D', 'E', 'D', 'D']],

       [['D', 'B', 'B', 'D', 'A'],
        ['D', 'B', 'D', 'D', 'D'],
        ['B', 'B', 'B', 'D', 'D']]], dtype=object)