# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
# your code here
import numpy as np
#Resulta que Numpy printa en notación científica por defecto ¬¬. 
#Desactivado en este lab para que se vea bien el ejercicio 16. 
np.set_printoptions(suppress=True) 

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.19.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [ ]:
# Method 1
#Distribución uniforme
a = np.random.rand(2,3,5)

In [3]:
# Method 2
a = np.random.randint(0,100,(2,3,5))

In [ ]:
# Method 3
#Normalmente distribuida (Gauss)
a = np.random.randn(2,3,5)

In [ ]:
#Distribución uniforme
a = np.random.random_sample((2,3,5))

#### 4. Print *a*.


In [4]:
# your code here
print(a)

[[[44 57 37 29 17]
  [75 64 80 93 64]
  [96 25 16 18 67]]

 [[23 47 56 27 78]
  [ 0 42 42 37 44]
  [59 52 83 37 64]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [5]:
# your code here
one_array = (5,2,3)
b = np.ones(one_array)

#### 6. Print *b*.


In [7]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [6]:
# your code here
if a.size == b.size:
    print(True)

True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [ ]:
# your answer here
# no, 'cause they don't have the same shape

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [7]:
# your code here
c = np.transpose(b, (1, 2, 0))

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [8]:
# your code/answer here
d = a + c
d
# It works because a and c have the same array shape

array([[[45., 58., 38., 30., 18.],
        [76., 65., 81., 94., 65.],
        [97., 26., 17., 19., 68.]],

       [[24., 48., 57., 28., 79.],
        [ 1., 43., 43., 38., 45.],
        [60., 53., 84., 38., 65.]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [9]:
# your code/answer here
print(a)
print(d)
# They do not concatenate like list do, d is just the addition of 1(from the array d) to each element in a.

[[[44 57 37 29 17]
  [75 64 80 93 64]
  [96 25 16 18 67]]

 [[23 47 56 27 78]
  [ 0 42 42 37 44]
  [59 52 83 37 64]]]
[[[45. 58. 38. 30. 18.]
  [76. 65. 81. 94. 65.]
  [97. 26. 17. 19. 68.]]

 [[24. 48. 57. 28. 79.]
  [ 1. 43. 43. 38. 45.]
  [60. 53. 84. 38. 65.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [12]:
# your code here
e = a*c

#### 13. Does *e* equal to *a*? Why or why not?


In [13]:
# your code/answer here
print(e)
print(a)
#They are similar but not the same, the numbers in e are floats while the numbers in a are integers

[[[46. 13.  8. 50.  2.]
  [53.  0. 50. 40. 26.]
  [47. 66. 91. 38. 88.]]

 [[34. 17. 61. 55. 44.]
  [66. 48. 60. 70. 65.]
  [14. 29.  4. 93. 42.]]]
[[[46 13  8 50  2]
  [53  0 50 40 26]
  [47 66 91 38 88]]

 [[34 17 61 55 44]
  [66 48 60 70 65]
  [14 29  4 93 42]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [12]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_max)
print(d_min)
print(d_mean)

97.0
1.0
50.1


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [10]:
# your code here
f = np.empty([2,3,5])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [23]:
# your code here
for x in range(len(d)):
    for y in range(len(d[x])):
        for z in range(len(d[x][y])):
            if d[x][y][z] > d_min and d[x][y][z] < d_mean:
                f[x][y][z]= 25
            elif d[x][y][z] < d_max and d[x][y][z] > d_mean:
                f[x][y][z]= 75
            elif d[x][y][z]== d_mean:
                f[x][y][z] = 50
            elif d[x][y][z] == d_min:
                f[x][y][z]= 0
            elif d[x][y][z] == d_max:
                f[x][y][z]= 100
print(f)

[[[ 25.  75.  25.  25.  25.]
  [ 75.  75.  75.  75.  75.]
  [100.  25.  25.  25.  75.]]

 [[ 25.  25.  75.  25.  75.]
  [  0.  25.  25.  25.  25.]
  [ 75.  75.  75.  25.  75.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here
for x in range(len(d)):
    for y in range(len(d[x])):
        for z in range(len(d[x][y])):
            if d[x][y][z] > d_min and d[x][y][z] < d_mean:
                f[x][y][z]= 25
            elif d[x][y][z] < d_max and d[x][y][z] > d_mean:
                f[x][y][z]= 75
            elif d[x][y][z]== d_mean:
                f[x][y][z] = 50
            elif d[x][y][z] == d_min:
                f[x][y][z]= 0
            elif d[x][y][z] == d_max:
                f[x][y][z]= 100
print(f)

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [26]:
# your code here
g = f.astype(dtype=str)
for x in range(len(d)):
    for y in range(len(d[x])):
        for z in range(len(d[x][y])):
            if d[x][y][z] > d_min and d[x][y][z] < d_mean:
                g[x][y][z]= 'A'
            elif d[x][y][z] < d_max and d[x][y][z] > d_mean:
                g[x][y][z]= 'B'
            elif d[x][y][z]== d_mean:
                g[x][y][z] = 'C'
            elif d[x][y][z] == d_min:
                g[x][y][z]= 'D'
            elif d[x][y][z] == d_max:
                g[x][y][z]= 'E'
print(g)

[[['A' 'B' 'A' 'A' 'A']
  ['B' 'B' 'B' 'B' 'B']
  ['E' 'A' 'A' 'A' 'B']]

 [['A' 'A' 'B' 'A' 'B']
  ['D' 'A' 'A' 'A' 'A']
  ['B' 'B' 'B' 'A' 'B']]]
