# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here

np.version.version

'1.19.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [48]:
# Method 1

a = np.random.rand(2,3,5)


In [49]:
# Method 2

z = np.random.randint(0,100,(2,3,5))
z

array([[[39, 61, 86, 65, 21],
        [ 6, 65, 89, 70, 77],
        [82, 46, 56, 68, 35]],

       [[15, 86, 79, 91, 21],
        [89, 95, 19, 41, 99],
        [68,  9, 55, 74, 36]]])

In [50]:
# Method 3


#### 4. Print *a*.


In [51]:
# your code here
a

array([[[0.68286092, 0.39487478, 0.00636452, 0.35136467, 0.47246238],
        [0.06299535, 0.8468558 , 0.18555378, 0.0860769 , 0.47047972],
        [0.71761544, 0.38900144, 0.12796947, 0.572908  , 0.27424022]],

       [[0.7284356 , 0.98325635, 0.96303219, 0.98376631, 0.07741707],
        [0.99615614, 0.73756946, 0.6304592 , 0.44847711, 0.72886835],
        [0.18466185, 0.92446311, 0.9101088 , 0.20122417, 0.20924825]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [52]:
# your code here

b = np.ones((5,3,2))

#### 6. Print *b*.


In [53]:
# your code here

b

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [54]:
# your code here

a.shape == b.shape

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [55]:
# your answer here

# NO, they must be the same shape in order to do so.

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [56]:
# your code here

c = np.transpose(b)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [57]:
# your code/answer here

d = a + c

# Arrays have the same shape

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [58]:
# your code/answer here

print(a)


print(d)

# Both arrays have the same dimensions. Array d is = to array a + 1.

[[[0.68286092 0.39487478 0.00636452 0.35136467 0.47246238]
  [0.06299535 0.8468558  0.18555378 0.0860769  0.47047972]
  [0.71761544 0.38900144 0.12796947 0.572908   0.27424022]]

 [[0.7284356  0.98325635 0.96303219 0.98376631 0.07741707]
  [0.99615614 0.73756946 0.6304592  0.44847711 0.72886835]
  [0.18466185 0.92446311 0.9101088  0.20122417 0.20924825]]]
[[[1.68286092 1.39487478 1.00636452 1.35136467 1.47246238]
  [1.06299535 1.8468558  1.18555378 1.0860769  1.47047972]
  [1.71761544 1.38900144 1.12796947 1.572908   1.27424022]]

 [[1.7284356  1.98325635 1.96303219 1.98376631 1.07741707]
  [1.99615614 1.73756946 1.6304592  1.44847711 1.72886835]
  [1.18466185 1.92446311 1.9101088  1.20122417 1.20924825]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [59]:
# your code here

e = a * c
e

array([[[0.68286092, 0.39487478, 0.00636452, 0.35136467, 0.47246238],
        [0.06299535, 0.8468558 , 0.18555378, 0.0860769 , 0.47047972],
        [0.71761544, 0.38900144, 0.12796947, 0.572908  , 0.27424022]],

       [[0.7284356 , 0.98325635, 0.96303219, 0.98376631, 0.07741707],
        [0.99615614, 0.73756946, 0.6304592 , 0.44847711, 0.72886835],
        [0.18466185, 0.92446311, 0.9101088 , 0.20122417, 0.20924825]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [60]:
# your code/answer here

e == a

# Both arrays are equal, Array a was multiplied by 1, so its values did not change.

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [64]:
# your code here

d_max = (np.amax(d))
print(d_max)
d_min = (np.amin(d))
print(d_min)
d_mean = (np.mean(d))
print(d_mean)


1.9961561430809973
1.006364519975174
1.5116255778260101


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [62]:
# your code here

f = np.empty((2,3,5))
f

array([[[0.68286092, 0.39487478, 0.00636452, 0.35136467, 0.47246238],
        [0.06299535, 0.8468558 , 0.18555378, 0.0860769 , 0.47047972],
        [0.71761544, 0.38900144, 0.12796947, 0.572908  , 0.27424022]],

       [[0.7284356 , 0.98325635, 0.96303219, 0.98376631, 0.07741707],
        [0.99615614, 0.73756946, 0.6304592 , 0.44847711, 0.72886835],
        [0.18466185, 0.92446311, 0.9101088 , 0.20122417, 0.20924825]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [67]:
# your code here

for x in range(f.shape[0]):
    if x >= d_min and x <= d_mean:
        x = 25
    if x >= d_mean and x <= d_max: 
        x = 75
    if x == d_min:
        x = 0
    if x == d_mean:
        x = 50
    if x == d_max:
        x = 100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [69]:
# your code here
print(f)

[[[0.68286092 0.39487478 0.00636452 0.35136467 0.47246238]
  [0.06299535 0.8468558  0.18555378 0.0860769  0.47047972]
  [0.71761544 0.38900144 0.12796947 0.572908   0.27424022]]

 [[0.7284356  0.98325635 0.96303219 0.98376631 0.07741707]
  [0.99615614 0.73756946 0.6304592  0.44847711 0.72886835]
  [0.18466185 0.92446311 0.9101088  0.20122417 0.20924825]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here